### ISSUE TITLE
RFC: Vue.js Options API support

### ISSUE THREAD

**Issue by franciscolourenco** [urql-graphql/urql#1327]
## Summary

Some people would prefer to keep using the Options API instead of the alternative Composition API.

The [Options API](https://v3.vuejs.org/api/options-api.html), as opposed to the Composition API, is the original way of creating Vue apps and components which can be found all over the [docs](https://v3.vuejs.org/guide/introduction.html#handling-user-input), in which an options object is passed to the Vue constructor, or exported in the case of [Single File Components](https://v3.vuejs.org/guide/single-file-component.html#introduction).

## Proposed Solution

A way to use urql using the declarative Options API in addition to the existing Composition API. The API could look something like the [vue-apollo API](https://apollo.vuejs.org/guide/apollo/#usage-in-vue-components)

**Comment by JoviDeCroock** [comment]
Could you elaborate on what the options api is, how an implementation would look like and so on? This isn't really an RFC rather than a request.

**Comment by franciscolourenco** [comment]
It was not my ambition to create a RFC, just a feature request. How this was the closest template which fitted the feature request case.
![image](https://user-images.githubusercontent.com/208149/105076974-1a69e180-5a8c-11eb-866b-aecbf778c285.png)

With that out of the way, the [Options API](https://v3.vuejs.org/api/options-api.html) as opposed to the Composition API, is the original way of creating Vue apps and components which can be found all over the [docs](https://v3.vuejs.org/guide/introduction.html#handling-user-input), in which an options object is passed to the Vue constructor, or exported in the case of [Single File Components](https://v3.vuejs.org/guide/single-file-component.html#introduction).

**Comment by franciscolourenco** [comment]
vue-apollo is an example of what supporting the Options API could look like https://apollo.vuejs.org/guide/apollo/queries.html#query-with-parameters

**Comment by kitten** [comment]
I'm wondering however, would it make sense to still provide an Options API if Vue 3 shows the Composition API front and centre. Our ambition was to support mostly Vue 3and this seemed to be the more idiomatic approach of the two at least there.
cc @LinusBorg: Do you have any insights on whether it'd be necessary or make sense to support both?

**Comment by franciscolourenco** [comment]
My understanding is that:

1. The majority of the docs is written with the Options API
1. There is a section in the docs for the Composition API
1. There is no intention to deprecate the Options API
1. The Composition API is not touted as the successor to the options API

**Comment by LinusBorg** [comment]
That's pretty much spot on on. the fact that the composition API right now take so much of the spotlight is just stemming from the fact that it's new and exciting.

It does solve real problems in areas of abstraction, composition and reusability, but the main API people are familiar with, and many/most new people probably pick up first, is still the Options API that remains largely unchanged from Vue 2.


So in that light it would be great if it would be supported. It should be possible to achieve it in a way that adds little overhead and uses the existing use* functions under the hood - I'll take a look, might take a bit though.

**Comment by franciscolourenco** [comment]
@kitten Could you share some context on the hold ⚠️ tag? Thanks!
