### ISSUE TITLE
RFC: Flexible key generation (override key field)

### ISSUE THREAD

**Issue by grconrad** [urql-graphql/urql#2698]
## Summary

When computing the key used to normalize data for given types, the graphcache Store `keyOfEntity` is hard-coded to use `id` or `_id` value if that's present.

```ts
    let key: string | null | void;
    if (this.keys[data.__typename]) {
      key = this.keys[data.__typename](data);
    } else if (data.id != null) {
      key = `${data.id}`;
    } else if (data._id != null) {
      key = `${data._id}`;
    }
```

Consumers can prevent the use of `id` / `_id` by passing `keys` to the `cacheExchange`, but that only works per specific type / typename. There's no way to override the behavior for all types.

I'm working in a project with a large existing GraphQL schema and API that uses a different field (which I'll call `anotherId`) to indicate uniqueness in nearly all of the (hundreds of) types. I can't ask the API teams to return these fields as `id`.

urql doesn't seem to support configuring a different field globally (in a way that isn't specific to a particular `__typename`). For obvious reasons it would be clumsy to have to parse the schema to find all the types with `anotherId` merely so I can specify all of those types (mapped to a single key generator function that returns `anotherId`) inside the `keys` config.

## Proposed Solution

A flexible solution would be to support callers providing their own function that computes the key for a piece of data. Callers could then implement their own logic that is type-specific (using `__typename`), checking for the presence of their own key fields, etc. and use `id` or `_id` only if their GraphQL schema uses those.

Note that Apollo Client's `InMemoryCache` uses that approach to support a global override function which is more flexible: [Customizing identifier generation globally](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-identifier-generation-globally)

**Comment by grconrad** [comment]
Update: It appears I can use a native `Proxy` here to implement my own logic.

```js
cacheExchange({
  // For 'keys' urql expects an object mapping __typename to a key gen function, to give us
  // control over the cache key per schema type. In the object mapping and in urql's logic that
  // consumes it there's no fallback mechanism where can say "for all types, use anotherId field
  // instead of id or _id field". It would be too cumbersome to process the schema dynamically
  // merely to map every __typename to a "use anotherId" key gen function. Instead, use a native
  // object proxy to define "use anotherId" as default behavior.
  keys: new Proxy(
    {
      SomeType: someCustomKeyGenFunction,
    },
    {
      get(target, prop, receiver) {
        // prop will be __typename when urql invokes the getter
        return (
          // If custom key gen is defined for this type, use that logic
          target[prop] ||
          // Otherwise use anotherId
          ((data) => data.anotherId || null)
        );
      }
    }
  ),
}),
```

**Comment by JoviDeCroock** [comment]
That is a creative solution, I would honestly opt for us to document this one 😅 I love keeping the API-surface small as that is something that can make for a lot of intuitive choices for consumers of the API. I have seen the need for this but haven't dug into the meat of the issue yet.

**Comment by kitten** [comment]
Marking this under `documentation`, so that we don't forget that this is to document the Proxy approach rather than implementing something new.
I actually tried this before as well myself, and it's what I'd recommend people to do, because it's a little more transparent, without us recommending everyone to come up with some super unexpected patterns for a `keys` function. I really wouldn't want most people to create a single `keys` function and then get stuck later on, so I really like recommending proxies here :+1:
