### ISSUE TITLE
RFC: Allow exchange-execute to execute even if context returns a Promise Function

### ISSUE THREAD

**Issue by YutaUra** [urql-graphql/urql#2805]
## Summary

In the current implementation, exchange-execute is expected to be an object or a function returning an object, but functions returning a Promise should also be supported

Specifically, I would like to get the following code working

```ts
export const serverSideUrqlLClient = createClient({
  exchanges: [
    // ...
    executeExchange({
      context: async () => {
        // Asynchronous processing of some kind.
        return {
          // ...
        }
      },
      schema: schema,
    }),
  ],
  url: `dummy`,
})
```

In the current implementation, even if contextValue is a Promise or a function that returns a Promise, the Promise is not properly handled.

## Proposed Solution

The contextValue must be resolved before the following is performed.

https://github.com/FormidableLabs/urql/blob/0b307a918242f5a8dadd977fd96b73b1b42d8c56/exchanges/execute/src/execute.ts#L55-L61

It looks like it would be better to add another `.then` just before and await the contextValue for that purpose.

## Requirements

Please also check the test cases and proposed implementation as a PR.

https://github.com/FormidableLabs/urql/pull/2806

## Thanks

Finally, thank you for creating a great library.

**Comment by kitten** [comment]
I'm not sure I understand what you mean here quite right. Basically the inputs expected are these: https://github.com/FormidableLabs/urql/blob/e7697fb7e558e936e03e884cd976468a963a386c/exchanges/execute/src/execute.ts#L112-L117

This simply gets mostly passed on to graphql.js's `execute` function. So, any utility or tool that outputs an executable schema or the necessary parts to use graphql's normal execution will work with this exchange

**Comment by YutaUra** [comment]
Thank you for your quick comment. And sorry for my unfamiliarity with OSS.

I have added a Summary for now. I will check a little more.
