### ISSUE TITLE
When two components use same query and error exists, both components keep fetching indefinitely.

### ISSUE THREAD

**Issue by chinnawatp** [urql-graphql/urql#2830]
### Describe the bug

**Actual Result**
First component fetches data and receives error. Second component fetches data and and receives error.
First component fetches data again, and Second component fetches data again.
It's keep going like this.

**Expected Result**
First component fetches data and receives error. Second component fetches data and and receives error.
Both components should not fetch anymore.

I think it's have something to do with import { cacheExchange } from "@urql/exchange-graphcache";.
Because If I remove cacheExchange, this issue doesn't occur.

**Reproduce Steps**
1. Open https://codesandbox.io/s/reproduce-urql-issue-same-query-infinite-fetch-5vtduk
2. Click "Show"
3. Inspect Console or Chrome > Inspect > Network
4. Both components will keep fetching

Thank you for any help in advance

### Reproduction

Urql - https://codesandbox.io/s/reproduce-urql-issue-same-query-infinite-fetch-5vtduk Apollo Server - https://codesandbox.io/s/urql-sample-apollo-server-7hy69m

### Urql version

3.0.3

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by nandorojo** [comment]
I've gotten this error too, I think due to schema awareness recognizing missing required fields.
