### ISSUE TITLE
Urql doesn't make a http request to the server on component remount and gets stuck on fetching.

### ISSUE THREAD

**Issue by xoldyckk** [urql-graphql/urql#2835]
### Describe the bug

I'm making a request to graphql server for an object using it's id. But the id is incorrect and no such object exists. So, the resolver checks the id and database for the object and if it doesn't exists throws a GraphqlError. Urql client receives this error in the graphQLErrors list on error object returned from the query. I'm checking the error object and rendering error message to the screen.

The first time this page is rendered everything works fine and the error message is rendered. But if I navigate away from the page and come back to it since the component unmounts and remounts urql client again makes the fetch request to the server because error results are not cached by urql I presume. 

The problem is that the refetch happens but urql client never sends a request to the server. I'm saying this because the fetching state returned from urql client turns to true. So, basically it gets stuck. Please look into this issue.

The codesandbox link I've attached shows two pages. User with id = 1 renders the data response. User with id != 1 renders the error response. Navigate away from the page and go back to it again. You can see the fetching state is stuck on fetching = true. In the network tab there's no request made to the server.

### Reproduction

https://codesandbox.io/p/github/xoldyckk/urql_nextjs_error/draft/tender-keldysh

### Urql version

urql v3.0.3
next-urql v4.0.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
I've taken a look and can confirm that this is an issue with the loop protection. We did recently fix another issue with it here, for reference: https://github.com/urql-graphql/urql/pull/2831

The original implementation is here: https://github.com/urql-graphql/urql/pull/2737

What we basically likely didn't account for are cases where the same query triggers again across multiple pages, i.e. explicit operations being triggered by the consuming client.

We'd likely have to find a way to better differentiate between `reexecuteOperation` loops and actual triggers in Graphcache, I'd suspect we'll need to take `teardown`s into account to check for this.

I'll see whether I can start a fix soon, and I'll link it to here once we do :v:

**Comment by kitten** [comment]
Ok, this was actually rather simple to fix 😅 Sorry for the delay!
