### ISSUE TITLE
Subscription doesn't update records after mutation

### ISSUE THREAD

**Issue by cinan** [urql-graphql/urql#2853]
### Describe the bug

Hello!

I believe I found a bug in urql subscriptions. I prepared a simple list, where users can add new records and rename existing ones. After a user creates a new record and after that they hit "Rename" button, updated results won't show up. The "Rename" button calls standalone gql client (not urql) just to simulate external source of change -- this way I'm sure urql doesn't know about mutation been called and so urql must update cache from subscription.

I also attached video: 

https://user-images.githubusercontent.com/1828134/205616233-c8c9d41e-e772-438f-a23f-c262d41e247e.mov

Or am I doing something wrong?

### Reproduction

https://github.com/cinan/urql-cache

### Urql version

@urql/exchange-graphcache: 5.0.5
urql: 3.0.3

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
A subscription isn't a datasource as much as a way to notify that something has changed, this distinction is important to your question. In GraphCache you can write updaters to update _query data_ when a subscription notifies you that an external entity has changed something to your data [docs](https://formidable.com/open-source/urql/docs/graphcache/cache-updates/).

This means that we should do the following instead:

- query the items by means of a `query`
- intercept additions/updates of items done by an external actor by means of a `subscription`
- intercept additions/updates of items done by yourself by means of a `mutation`
