### ISSUE TITLE
__typename is missing after upgrading from @urql/core 3.0.5 to 3.1.0

### ISSUE THREAD

**Issue by mech** [urql-graphql/urql#2869]
### Describe the bug

After upgrading, I noticed all my `__typename` are gone. Do I need to explicitly specify them in my query?

This work on 3.0.5 without specifying `__typename` in the selection:

```
query {
  notes {
    id
    name
  }
}
```

From the default test codesandbox you can see the `__typename` is missing.

### Reproduction

https://codesandbox.io/s/friendly-engelbart-sb00j4?file=/package.json

### Urql version

urql = 3.0.3
@urql/core = 3.1.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by mech** [comment]
<img width="1054" alt="fc6f3_16_18_50" src="https://user-images.githubusercontent.com/5850/206656802-637249f8-cff1-4ab2-82bc-a6f5ab69c376.png">

**Comment by JoviDeCroock** [comment]
Fixed by #2871
