### ISSUE TITLE
Types not available for next-urql after upgrading to 4.0.1

### ISSUE THREAD

**Issue by garth** [urql-graphql/urql#2873]
### Describe the bug

typescript error: Could not find a declaration file for module 'next-urql'

Was fine with v4.0.0.

I'm using pnpm to manage dependencies.

### Reproduction

n/a

### Urql version

next-urql 4.0.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
Related to #2868

**Comment by cinan** [comment]
also types for `@urql/exchange-graphcache` 5.0.6 seems to be broken, 5.0.5 was fine

**Comment by JoviDeCroock** [comment]
We're working on it

**Comment by Manubi** [comment]
> also types for `@urql/exchange-graphcache` 5.0.6 seem to be broken, 5.0.5 was fine

I saw updated version, but the typings error is still there.
