### ISSUE TITLE
RFC: change the way urql do pagination

### ISSUE THREAD

**Issue by andresribeiro** [urql-graphql/urql#2916]
## Sumary

The current way urql handles infinite pagination is with simplePagination and relayPagination. The documentation itself says that these 2 functions do not satisfy all cases of infinite pagination, creating a barrier to migrating from other libraries in specific scenarios.

## Proposed Solution

My proposal is, in useQuery, to return a loadMore function, which will have an updateQuery function, just like in other GraphQL clients.

**Comment by JoviDeCroock** [comment]
Honestly think that isn't really the concern of the hook itself, paginating is part of the view so from the urql-team we always advise to keep this a UI concern, hence our example highlights this https://github.com/urql-graphql/urql/blob/main/examples/with-pagination/src/PaginatedNpmSearch.jsx where we have a `useQuery` for every page.

**Comment by andresribeiro** [comment]
I have an example where the result of a query is a Union, which can return "UserPrivate" or "UserPostsConnection". Notice that in this case, I can't use relayPagination since it expects it to be the mandatory UserPostsConnection?

Another solution I think would be to have my own pagination function, like these 2 in the documentation, but currently each of these 2 functions are too complex to create. Looking at the code of the existing functions, you have to manually resolve the cache and make a comparison with the args. The simplePagination file alone has 112 lines

**Comment by JoviDeCroock** [comment]
Mainly referring to the UI approach which seems more complete 😅 as you seem to be alluding to the resolvers approach here

**Comment by andresribeiro** [comment]
Variables (but could be passed to the pagination with the resolvers via the query itself) and keep the code closer. If one deletes a query, one might forget to remove the pagination from it in the resolvers. If they forget it would be no big deal, but I think it would be a good practice to keep the code closer.

**Comment by development-vargamarcel** [comment]
Bellow I define, most types of pagination present in graphql endpoints. This is an approach I am testing in a library I am working on. Having that, pagination will work on any graphql endpoint, and is easy to add a new pagination type if is custom. 
Note that this is not complete. 
If you are interested, I can provide link to live demo. 
Also I support in the same fashion, the ability to get row count for given query, that updates when args change, like filters.... Much more to say, if you want to know more let me know. 
`
import { getDataGivenStepsOfFields } from "$lib/utils/usefulFunctions"
import { get } from "svelte/store"
import { endpointInfo } from "../endpointInfo/endpointInfo"
import { schemaData } from "../schemaData"


//console.log('asdasdasda', endpointInfo)
export const paginationTypes = [
    {
        name: 'notAvailable', get_rowLimitingArgNames: (paginationArgs) => {
            return []

        }, get_initialState: (paginationArgs) => {
            console.log('notAvailable')
        }, get_defaultPaginationStateForDynamic: (state) => {
            return state
        }, get_dependencyColsData: (QMS_name) => {
            return []
        }, get_nextPageState: (state, paginationArgs) => {
            console.log('notAvailable')
        }, get_prevPageState: (state, paginationArgs) => {
            console.log('notAvailable')
        }, isFirstPage: (_pagination_state_Store, paginationArgs) => { return true }, check: (standsForArray) => {
            return standsForArray.length == 0
        }
    },
    {
        name: 'offsetBased', get_rowLimitingArgNames: (paginationArgs) => {
            const limitName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'limit' })?.dd_displayName
            return [limitName]

        }, get_initialState: (paginationArgs) => {
            const offsetName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'offset' })?.dd_displayName
            const limitName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'limit' })?.dd_displayName
            return {
                [limitName]: 20,
                [offsetName]: 0
            }

        }, get_dependencyColsData: (QMS_name) => {
            return []
        }, get_defaultPaginationStateForDynamic: (state, paginationArgs) => {
            const offsetName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'offset' })?.dd_displayName
            const _state = JSON.parse(JSON.stringify(state))
            _state[offsetName] = 0
            return _state
        }, get_nextPageState: (state, paginationArgs) => {
            const offsetName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'offset' })?.dd_displayName
            const limitName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'limit' })?.dd_displayName
            const _state = JSON.parse(JSON.stringify(state))
            _state[offsetName] += _state[limitName]
            return _state
        }, get_prevPageState: (state, paginationArgs) => {
            const offsetName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'offset' })?.dd_displayName
            const limitName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'limit' })?.dd_displayName
            const _state = JSON.parse(JSON.stringify(state))
            _state[offsetName] -= _state[limitName]
            return _state
        }, isFirstPage: (_pagination_state_Store, paginationArgs) => {
            const offsetName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'offset' })?.dd_displayName
            return !get(_pagination_state_Store)?.[offsetName] > 0

        }, check: (standsForArray) => {
            return standsForArray.includes('limit') && standsForArray.includes('offset')
        }
    },
    {
        name: 'edgeBased', get_rowLimitingArgNames: (paginationArgs) => {
            const firstName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'first' })?.dd_displayName
            const lastName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'last' })?.dd_displayName
            return [firstName, lastName]
        }, get_initialState: (paginationArgs) => {
            const firstName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'first' })?.dd_displayName
            return {
                [firstName]: 20,
            }

        }, get_defaultPaginationStateForDynamic: (state, paginationArgs) => {
            const afterName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'after' })?.dd_displayName
            const beforeName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'before' })?.dd_displayName
            let _state = JSON.parse(JSON.stringify(state))
            delete _state[afterName]
            delete _state[beforeName]
            return _state
        }, get_dependencyColsData: (QMS_name, QMS_type) => {
            //using 'pageInfo' for getting next page cursor,'nextPage' is not a standard,some use another name like 'endCursor' { title: 'nextPageCursor', stepsOfFields: [QMS_name, 'pageInfo', 'nextPage'] }
            const dependencyColsData = []
            const endpointInfoVal = get(endpointInfo)
            const namings = endpointInfoVal?.namings
            const pageInfoFieldsLocation = endpointInfoVal.pageInfoFieldsLocation
            let currentQMS_Info = schemaData.get_QMS_Field(QMS_name, QMS_type);
            const rowsLocation = endpointInfo.get_rowsLocation(currentQMS_Info);

            if (namings?.endCursor || namings?.startCursor) {
                if (namings?.hasNextPage) {
                    dependencyColsData.push({ title: namings.hasNextPage, hidden: true, stepsOfFields: [QMS_name, ...pageInfoFieldsLocation, namings.hasNextPage] })
                }
                if (namings?.hasPreviousPage) {
                    dependencyColsData.push({ title: namings.hasPreviousPage, hidden: true, stepsOfFields: [QMS_name, ...pageInfoFieldsLocation, namings.hasPreviousPage] })
                }
                if (namings?.startCursor) {
                    dependencyColsData.push({ title: namings.startCursor, hidden: true, stepsOfFields: [QMS_name, ...pageInfoFieldsLocation, namings.startCursor] })
                }
                if (namings?.endCursor) {
                    dependencyColsData.push({ title: namings.endCursor, hidden: true, stepsOfFields: [QMS_name, ...pageInfoFieldsLocation, namings.endCursor] })
                }
                return dependencyColsData
            }


            if (namings?.cursor) {
                dependencyColsData.push({ title: namings.cursor, stepsOfFields: [QMS_name, ...rowsLocation, namings.cursor] })
            }
            return dependencyColsData




        }, get_nextPageState: (state, paginationArgs, returnedDataBatch_last, QMS_name, QMS_type) => {
            const endpointInfoVal = get(endpointInfo)
            const namings = endpointInfoVal?.namings
            let currentQMS_Info = schemaData.get_QMS_Field(QMS_name, QMS_type);
            const pageInfoFieldsLocation = endpointInfoVal.pageInfoFieldsLocation
            const rowsLocation = endpointInfoVal.rowsLocationPossibilities.find(
                (rowsLocation) => {
                    return rowsLocation.check(currentQMS_Info);
                }
            ).rowsLocation;

            const afterName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'after' })?.dd_displayName
            const stepsOfFieldsToCursor = ['edges', 'cursor']
            const stepsOfFieldsToEndCursor = [QMS_name, ...pageInfoFieldsLocation, namings.endCursor]
            const _state = JSON.parse(JSON.stringify(state))
            if (namings?.endCursor && returnedDataBatch_last) {
                let endCursorValue = getDataGivenStepsOfFields(undefined, returnedDataBatch_last, stepsOfFieldsToEndCursor)
                if (endCursorValue) {
                    _state[afterName] = `'${endCursorValue}'`
                }
                console.log({ _state }, { returnedDataBatch_last })
            } else
                if (namings?.cursor) {
                    let rows = getDataGivenStepsOfFields(undefined, returnedDataBatch_last, [currentQMS_Info.dd_displayName, ...rowsLocation])
                    let lastRow = rows[rows.length - 1]
                    console.log({ lastRow })
                    _state[afterName] = `'${getDataGivenStepsOfFields(undefined, lastRow, stepsOfFieldsToCursor)}'`
                    console.log({ _state })
                }
            return _state
        }, get_prevPageState: (state, paginationArgs, returnedDataBatch_last, QMS_name) => {
            const _state = JSON.parse(JSON.stringify(state))
            return _state
        }, isFirstPage: (_pagination_state_Store, paginationArgs) => {
            const afterName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'after' })?.dd_displayName
            const beforeName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'before' })?.dd_displayName
            return !get(_pagination_state_Store)?.[afterName] && !get(_pagination_state_Store)?.[beforeName]
        }, check: (standsForArray) => {
            return standsForArray.includes('first') || standsForArray.includes('last') && standsForArray.includes('after') || standsForArray.includes('before')
        }
    },
    {
        name: 'pageBased', get_rowLimitingArgNames: (paginationArgs) => {
            const page = paginationArgs.find((arg) => { return arg.dd_standsFor == 'page' })?.dd_displayName
            return [page]
        }, get_initialState: (paginationArgs) => {
            const pageName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'page' })?.dd_displayName
            return {
                [pageName]: 1
            }
        }, get_dependencyColsData: (QMS_name) => {
            return []
        }, get_defaultPaginationStateForDynamic: (state, paginationArgs) => {
            const pageName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'page' })?.dd_displayName
            let _state = JSON.parse(JSON.stringify(state))
            _state = { ..._state, [pageName]: 1 }
            return _state
        }, get_nextPageState: (state, paginationArgs) => {
            const pageName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'page' })?.dd_displayName
            const _state = JSON.parse(JSON.stringify(state))
            _state[pageName]++
            return _state
        }, get_prevPageState: (state, paginationArgs) => {
            const pageName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'page' })?.dd_displayName
            const _state = JSON.parse(JSON.stringify(state))
            _state[pageName]--
            return _state
        }, isFirstPage: (_pagination_state_Store, paginationArgs) => {
            let pageName = paginationArgs.find((arg) => { return arg.dd_standsFor == 'page' })?.dd_displayName
            return get(_pagination_state_Store)?.[pageName] == 1
        }, check: (standsForArray) => {
            return standsForArray.includes('page')
        }
    },
    {
        name: 'unknown', get_rowLimitingArgNames: (paginationArgs) => {
            return []

        }, get_initialState: (paginationArgs) => {
            console.log('unknown')
        }, get_defaultPaginationStateForDynamic: (state) => {
            return state
        }, get_dependencyColsData: (QMS_name) => {
            return []
        }, get_nextPageState: (state, paginationArgs) => {
            console.log('unknown')
        }, get_prevPageState: (state, paginationArgs) => {
            console.log('unknown')
        }, isFirstPage: (_pagination_state_Store, paginationArgs) => { return true }, check: (standsForArray) => {
            return standsForArray.length == 0
        }
    },
]
`

**Comment by andresribeiro** [comment]
hey @kitten

thanks, i think i've missed that part from the docs, but this UI Pattern wouldn't work with a virtualized list, like FlatList on React Native

i thought of doing it somehow like this:

```jsx
const [pageVariables, setPageVariables] = useState([
  {
    first: 10,
    after: '',
  },
]);

const myInfiniteList = pageVariables.map(pageVariable => {
  return urqlClient.executeQuery(
    /* variables */
  )
})
```

that way I would have all my data in a single array to use in my virtualized list

do you have any ideas, maybe something about any performance issues this might cause?
