### ISSUE TITLE
useQuery calling setState in render body.

### ISSUE THREAD

**Issue by subskribe-kevin** [urql-graphql/urql#2939]
### Describe the bug

I'm pretty sure we stumbled upon a big in useQuery.

You're calling setState in the body when in needs to be wrapped in a useEffect

https://reactjs.org/link/setstate-in-render%s

We're getting the error:

> (5) ['Warning: Cannot update a component (`%s`) while re… in https://reactjs.org/link/setstate-in-render%s',

I believe it's being triggerd by this code block here:

https://github.com/urql-graphql/urql/blob/main/packages/react-urql/src/hooks/useQuery.ts#L155

(line 155)

>  let currentResult = state[1];
>  if (source !== state[0] && hasDepsChanged(state[2], deps)) {
>    setState([
>      source,
>      (currentResult = computeNextState(
>        state[1],
>        getSnapshot(source, suspense)
>      )),
>      deps,
>    ]);
>  }

which needs to be wrapped in a useEffect because setState can't be called from
the render body.

I think the fix is as easy as just putting it in a useEffect.

I don't mind submitting a PR for this if you think I'm correct and this would
be a valid solution.

### Reproduction

The reproduction is your own code as by definition calling setState in the render body is wrong.  If you require a reproduction it's going to take me hours to get you one as it's difficult to reproduce.  

### Urql version

3.0.3.

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
So, long story short, this statement isn't entirely true:

> The reproduction is your own code as by definition calling setState in the render body is wrong

For reference, we've observed other concurrent-compatible implementations, have spoken to the React team, have worked with a member of them to verify and improve our implementation, have cross-checked this in the past against [use-subscription](https://github.com/facebook/react/tree/main/packages/use-subscription), and I've also worked on react-ssr-prepass and am hence familiar with some internal mechanisms of hooks.

To give some short context, updating state in this manner in a render cycle is not invalid and is intended. In fact, it may bail out of an optimisation to prevent tearing, then starts the render cycle again with the updated state. This is exactly intended to synchronise the state and ensure that an update isn't delayed behind an effect and queued up.

What you're seeing in the output is basically a warning — and this warning can misfire. We've already observed that something in React Native erroneously triggers it and we can't find any negative effects of it and it's safe to ignore in that case.

We used to actually have a flawed workaround that would hide this warning. When we found out in which manner it was flawed, it was removed and hence these warnings returned on React Native apps (again; with no discernible side effect: https://github.com/urql-graphql/urql/pull/2556

There's other issues open for this but for now I can only find this: https://github.com/urql-graphql/urql/issues/2773
I'm closing this issue as a duplicate for now, as it again doesn't outline any negative side-efdecrs and doesn't unfortunately add more information. So we'll still continue to assume that it's a misfiring warning.
