### ISSUE TITLE
(vue) - Pausing subscription does not end the connection

### ISSUE THREAD

**Issue by Ancient-Dragon** [urql-graphql/urql#2990]
### Describe the bug

We create a subscription on our application start, however when a user clicks a button it changes a variable and we pause and resume the subscription so that the subscription gets updated with the latest variable. This kicks off a new http requests, however it does not complete the old request. Therefore we are left with two HTTP requests open to the server, both pushing data to our application causing issues.

We are using graphql-sse so see the guide on how to install here.
https://github.com/enisdenjo/graphql-sse#urql

I think there are a few ways to approach this, one could be to offer a stop method on the subscription allowing the user to control this would be great, this should finish the request (whether that's a http or ws request). 

Alternatively continue to use the pause but have it actually cancel the request. (I thought this is done by calling the unsubscribe method but it doesn't look to be working if it is)

### Reproduction

TBD

### Urql version

    "@urql/vue": "^1.0.4",
    "graphql-sse": "^2.0.0",

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Just a quick note, I've checked the Vue bindings and don't see an obvious issue in the implementation. Also for completeness' sake, it's definitely expected that the original subscription is cancelled (i.e. the `Client` source will be unsubscribed from) during `pause` being set.

If you'd like to speed up the debugging process, which would help out tremendously, you can use this as a template: https://github.com/urql-graphql/urql/tree/main/examples/with-vue3

**Comment by Ancient-Dragon** [comment]
I'll try get around to create a reproducible example. Do you guys need an example server as well? 

Here are some logs I pulled (which can hopefully help): 
```
Debugging Subscription: resume
Debugging Subscription: is paused changed RefImpl {__v_isShallow: false, dep: Set(2), __v_isRef: true, _rawValue: false, _value: false}
Debugging Subscription: Exchange Subscribe {key: '-48ie89b', query: 'subscription … {\n        value\n        hint\n      }\n    }\n  }\n}', variables: Proxy, context: {…}}
Debugging Subscription: pause - is paused: true
Debugging Subscription: resume
Debugging Subscription: is paused changed RefImpl {__v_isShallow: false, dep: Set(2), __v_isRef: true, _rawValue: false, _value: false}
Debugging Subscription: Exchange Subscribe {key: '-48ie7f2', query: 'subscription … {\n        value\n        hint\n      }\n    }\n  }\n}', variables: Proxy, context: {…}}
Debugging Subscription: pause - is paused: false
Debugging Subscription: is paused changed RefImpl {__v_isShallow: false, dep: Set(2), __v_isRef: true, _rawValue: true, _value: true}
Debugging Subscription: Exchange unsubscribe
Debugging Subscription: resume
Debugging Subscription: is paused changed RefImpl {__v_isShallow: false, dep: Set(2), __v_isRef: true, _rawValue: false, _value: false}
Debugging Subscription: Subscribe {key: '-48ie89b', query: 'subscription … {\n        value\n        hint\n      }\n    }\n  }\n}', variables: Proxy, context: {…}}
```
From the above I can see the first time I'm calling pause it runs the method but doesn't call unsubscribe (also my watcher isn't triggered - but what is interesting is that it says isPaused is true before I even call pause, but I haven't called resume as far as I can tell). Then it calls resume, which triggers a new subscription in the exchange. Then I click to pause again which triggers the pause method this time the watcher is called and the unsubscribe method is called as expected.

However this still leaves two subscriptions open. 
App.vue:
```ts
const client = createClient({
  url: import.meta.env.VITE_GRAPHQL_QUERY_ENDPOINT,
  exchanges: [
    dedupExchange,
    cacheExchange,
    authExchange({
      getAuth,
      addAuthToOperation,
      didAuthError,
    }),
    persistedFetchExchange(),
    multipartFetchExchange,
    subscriptionExchange({
      forwardSubscription(operation) {
        return {
          subscribe: (sink) => {
            console.info('Debugging Subscription: Subscribe', operation);
            const dispose = sseClient.subscribe(operation, sink);
            const callingSubscribe = () => {
              console.info('Debugging Subscription: unsubscribe');
              dispose();
            };
            return {
              unsubscribe: callingSubscribe,
            };
          },
        };
      },
    }),
  ],
});
```


Composable:
```ts
  const subscription= useSubscription<Response>({
    query: SUBSCRIPTION,
    variables,
    pause: true,
  }, (response, data) => {
    // ...
    return data;
  });

  const listenForUpdates = (date: DateTime) => {
    variables.date= date.toFormat('yyyy-MM-dd');
    console.info('Debugging Subscription: resume');
    subscription.resume();
  };

  watch(subscription.isPaused, () => {
    console.info('Debugging Subscription: is paused changed', subscription.isPaused);
  });
  const unsubscribeFromUpdates = () => {
    console.info('Debugging Subscription: pause', susbcription.isPaused);
    subscription.pause();
  };
```

**Comment by kitten** [comment]
> Do you guys need an example server as well?

You can use anything you want really; this isn't really down to what we need, but what you need to reproduce it.

Basically, I can ask for more information manually until I narrow down what to look at, or create a reproduction myself (at which point we had situations in the past, where we couldn't reproduce issues or there was no issue in the first place 😅), or I can start digging through _all_ affected/used code until I find an issue (or not).
So, that's all very time intensive and that's why we kindly ask for a reproduction. The reality unfortunately is that with this many moving parts it's easier for you than it is for us to start narrowing this down.

That's why we host the `examples` folder primarily actually 👀 But we also have testing APIs: https://trygql.formidable.dev/
Unfortunatly, we currently have no example API that we can provide you for `graphql-sse` or `graphql-ws` just yet
So, I do hope it won't take too much work ❤️

**Comment by Ancient-Dragon** [comment]
Thanks for the help when I tried to reproduce with a local example I could see that it was working as you described. Which lead me to an idea (essentially what happened was I had two instances of the composable and therefore two instances of the subscription running, idiotic of me!). Apologies for raising the ticket closing it now. Again thanks for the help.

**Comment by kitten** [comment]
No worries!
