### ISSUE TITLE
fix: `IntrospectionData` gone in `@urql/exchange-graphcache` v5.2.0

### ISSUE THREAD

**Issue by dargmuesli** [urql-graphql/urql#3027]
### Describe the bug

In v5.0.9 I used `import { IntrospectionData } from '@urql/exchange-graphcache/dist/types/ast'` but that does not work anymore in v5.2.0. In the new version I see `IntrospectionData` as non-exported type in `dist/urql-exchange-graphcache-chunk.d.ts`. Am I not supposed to access it anymore?

### Reproduction

will provide if description is not clear already

### Urql version

@urql/exchange-graphcache 5.2.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by dargmuesli** [comment]
2db32951dbfdb849616a909721ee1085b99096e3 somehow didn't keep the exports, could that be?

**Comment by JoviDeCroock** [comment]
Generally it's not really the purpose to rely on nested imports when they're not defined in the [`export-maps`](https://github.com/urql-graphql/urql/blob/main/exchanges/graphcache/package.json#L26) as these are considered internal. We could however export this type and as an in-between `typeof CacheExchangeOpts['schema']` offers the same result.

**Comment by kitten** [comment]
Just to note as well, for an ESM export, this import wouldn't even work 😅 Technically speaking only `import type { IntrospectionData } from '@urql/exchange-graphcache/dist/types/ast'` is valid, but as Jovi already said, there are other ways to get to this type, and as we bundle our JS (and now our types too), file drilling is not allowed anymore. It isn't even a publicly maintained way to import stuff 😅 Sorry!

**Comment by dargmuesli** [comment]
Thank you for the information and alternatives!
