### ISSUE TITLE
Unsafe ref usage in urql-react

### ISSUE THREAD

**Issue by marcusdarmstrong** [urql-graphql/urql#3047]
### Describe the bug

Hi, after implementing a lint to identify this pattern in our own codebase, I figured I'd mention it here. React's (new) prescribed documentation about how Refs should be utilized is pretty explicit (in multiple places) that ref values shouldn't be read or written to during component render time. 

> You shouldn’t read (or write) the current value during rendering.
- https://beta.reactjs.org/learn/referencing-values-with-refs#differences-between-refs-and-state

I've identified a couple of locations where this is being violated in urql—it's possible that this is driving some of the difficulties you've had in the past with `useSyncExternalStore`, though I haven't dug in too deeply.

1. https://github.com/urql-graphql/urql/blob/main/packages/react-urql/src/hooks/useRequest.ts#L23 (This, of course, extends to all usages of useRequest, since it's returning a ref.)
2. https://github.com/urql-graphql/urql/blob/main/packages/react-urql/src/hooks/useSubscription.ts#L62 (This one is less significant, correctness here is trivially achieved by wrapping that set in a `useEffect`.)

Apologies for not having a proper reproduction link, but I figured it was at least worth mentioning and `bug` seemed like the appropriate terminology.

### Reproduction

It's unclear what exactly is the outcome of violating these react invariants, such that I cannot provide a reproduction case.

### Urql version

The issue is present in `main`.

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Similar answer to here: https://github.com/urql-graphql/urql/issues/2939#issuecomment-1410852434
All usages in react-urql are validated to be safe
Hence, unless you see a specific, reproducible bug, we cannot accept issues without concrete evidence of incorrect behaviour

**Comment by marcusdarmstrong** [comment]
Given that this is the documented contract of `useRef`, however, you can only really say you've validated react-urql's behavior for a particular set of react versions—and an arbitrary patch version of react could break that validation.
