### ISSUE TITLE
Typescript integration for Svelte is missleading

### ISSUE THREAD

**Issue by hahn-kev** [urql-graphql/urql#3110]
### Describe the bug

In the documentation for Typescript integration it reccomends using this configuration:
```js
const config: CodegenConfig = {
  schema: '<YOUR_GRAPHQL_API_URL>',
  documents: ['src/**/*.svelte'],
  ignoreNoDocuments: true, // for better experience with the watcher
  generates: {
    './src/gql/': {
      preset: 'client',
      plugins: [],
    },
  },
};

export default config;
```

specifically documents references `.svelte` files meaning you could write querys in your svelte files and they would be parsed and have types generated for them. However this is not the case. None of the svelte gql type generating libraries parse the actual `.svelte` files to look for queries.

I considered making a PR to fix this myself but I'm not sure how documentation fixes get handled. Sorry if this is the wrong place to report this issue.

### Reproduction

https://formidable.com/open-source/urql/docs/basics/typescript-integration/

### Urql version

https://formidable.com/open-source/urql/docs/basics/typescript-integration/

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Just to clarify here, feel free to send a docs PR ✌️, I don't currently have the bandwidth to see how this is supposed to work, or how svelte file support looks like currently in GCG

**Comment by JoviDeCroock** [comment]
It looks like we need a few disclaimers as according to their documentation it is possible when using SvelteKit https://the-guild.dev/graphql/codegen/docs/guides/svelte#sveltekit-native
