### ISSUE TITLE
Type mismatch of FetchBody and graphql-ws SubscribePayload

### ISSUE THREAD

**Issue by florianwittmann** [urql-graphql/urql#3126]
### Describe the bug

From the latest 4.0.0 urql release, the subscription example with graphql-ws (https://formidable.com/open-source/urql/docs/advanced/subscriptions/#setting-up-graphql-ws) does result in a typescript error because of a mismatch of the types of `FetchBody` (urql) and `SubscribePayload`(graphql-ws).

Error:
```
Argument of type 'FetchBody' is not assignable to parameter of type 'SubscribePayload'.
  Types of property 'query' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.ts(2345)
```

### Reproduction

https://github.com/florianwittmann/urql4-subscriptions-type-mismatch

### Urql version

urql: "4.0.0"
graphql-ws: "5.12.1"

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
Is it possible you are referring to this https://github.com/urql-graphql/urql/discussions/3121

**Comment by florianwittmann** [comment]
@JoviDeCroock
Yes, seems to be the same. Should the documentation add some of the suggested solutions in the example (https://formidable.com/open-source/urql/docs/advanced/subscriptions/#setting-up-graphql-ws)?
