### ISSUE TITLE
"undefined is not a function" from wonka.js on query operation in react-native

### ISSUE THREAD

**Issue by jtc3161** [urql-graphql/urql#3129]
### Describe the bug

Using a minimal example mostly copied from the docs I'm getting the error "undefined is not a function" when a useQuery attempts to execute the operation. This is specifically happening on Android using expo@48 (react-native dev environment). There is some incompatibility with urql@4 and expo@48 that I haven't been able to get to the bottom of.

Debugger is pointing to this line as the entry to wonka.js: https://github.com/urql-graphql/urql/blob/b7b14a40e68e74f0f8ea90ee407514e9336c2c09/packages/core/src/internal/fetchSource.ts#L198

The provided reproduction doesn't work in the snack web ui, but if you download the zip, run:
`npm install` `npx expo start` and then use the Expo Go app to run it on an android phone and it runs fine. But then if you run `npm uninstall expo` and then `npm install expo@48` (newest version), urql does not function properly. I'll continue to work on tracking down what package exactly is causing the incompatibility. upgrading expo also upgrades react-native and several other packages.

btw love this project, I have multiple web apps using urql and they have always worked flawlessly.

### Reproduction

https://snack.expo.dev/@jtc3161/curious-chip?platform=web

### Urql version

urql v4.0.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
I'm not sure what Expo's default transpilation for node modules comes down to, since I've actually seen that their preset includes this, but to summarise, the problem here is that you'll need to add a transformer for async generators, so it's not a bug per se, but React Native is basically the only supported platform that doesn't have support for async iterables/generators out of the box and will need that to be transpiled.

This on its own isn't that unusual — after all — Hermes has a bunch of unsupported ES features that are a little odd compared to other platforms, but generally speaking, I'm basically just not sure what Expo's default's on this are or what Expo Snack's defaults for this are.

**Comment by jtc3161** [comment]
Awesome thank this is an amazing lead. I'll hit up the expo discord. If there's any react-native specific urql documentation I might be able to provide I will get back to you

**Comment by jtc3161** [comment]
@kitten thank you for your help, digging into the docs, expo 48 changed the default js engine from JS core to Hermes. Switching the engine back to jscore unblocks me, but it doesn't seem like this has ever worked on hermes. I have an issue open on expo to see if there's changes that can be made to their babel preset to support this.

**Comment by Vednus** [comment]
Is there a workaround for this that anyone knows of? Going back to JS core is a bad idea. Hermes has been the default for a while now. I'll look into it and post any options I come across.

**Comment by Vednus** [comment]
seems like this will work: https://github.com/aws-amplify/amplify-js/issues/10764#issuecomment-1363140556

**Comment by Mafooch** [comment]
So, is the official fix for this just to use the js core polyfill or should we be expecting an update from urql?

**Comment by kitten** [comment]
@Mafooch We're not currently planning a change from our end, no, as the switch to async generators on our fetch implementation was intentional given our browser support. That said, while Hermes is not supporting async generators/iterables — and you can work around this by ensuring the proper polyfills and transforms are applied — the React Native Babel preset _should_, as long as it's applied to node modules, polyfill support for this.

However, for one reason or another this doesn't seem to be the case. The only issue that was opened in reaction to this is: https://github.com/expo/expo/issues/22006#issuecomment-1502101078

However, I currently have no bandwidth to look into this and am not sure why this polyfill may not be applied correctly automatically

**Comment by elisalimli** [comment]
@Vednus @jtc3161 

> seems like this will work: [aws-amplify/amplify-js#10764 (comment)](https://github.com/aws-amplify/amplify-js/issues/10764#issuecomment-1363140556)

Is just adding this to index.ts solved the issue for you?

```tsx 

import "core-js/full/symbol/async-iterator";
import allSettled from "promise.allsettled";
allSettled.shim();

import "expo-router/entry";

```

**Comment by Vednus** [comment]
@elisalimli I think that's what I did. I ended up not going with urql, but I'm pretty sure that worked

**Comment by elisalimli** [comment]
@Vednus In my case adding the lines to index.ts fixed the "undefined is not a function" error. 

But while using useQuery network error occurs:

`
 [Network] Cannot convert undefined value to object
    at construct (native)
    at apply (native)
    at _construct (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:7125:28)
    at Wrapper (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:7087:25)
    at construct (native)
    at _createSuperInternal (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:128706:294)
    at call (native)
    at CombinedError (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:128742:26)
    at makeErrorResult (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:129002:31)
    at ?anon_0_ (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:129326:30)
    at throw (native)
    at resume (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:129380:30)
    at anonymous (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:129391:17)
    at tryCallOne (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:33521:26)
    at _callTimer (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:33440:17)
    at _callReactNativeMicrotasksPass (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:33470:17)
    at callReactNativeMicrotasks (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:33633:44)
    at __callReactNativeMicrotasks (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:6570:46)
    at anonymous (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:6382:45)
    at __guard (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:6554:15)
    at flushedQueue (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:6381:21)
    at callFunctionReturnFlushedQueue (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:6366:33)
`

>  I ended up not going with urql
What was the actual reason? these errors or something else ?

**Comment by elisalimli** [comment]
@Vednus can you share the link to the working code, please? I'm just trying to debug this error and can't solve it.

**Comment by Vednus** [comment]
@elisalimli I don't have any working code to show you. I have that work in a branch, but it's in a private repo and in a large project. I think the error you're getting probably means your useQuery code is wrong, like you didn't destructure correctly or something along those lines.

**Comment by Vednus** [comment]
@elisalimli you're importing "gel", but "gel" isn't a thing. I think you're meaning to import "gql" and that's why you're erroring out.

**Comment by elisalimli** [comment]
I don't know why that happened. But in my code it's `gql` not `gel`

**Comment by Vednus** [comment]
@elisalimli then I don't know. Good luck

**Comment by elisalimli** [comment]
@Vednus btw why are you not using react-query instead of Apollo? It looks like it has got a bunch of features

**Comment by Vednus** [comment]
@elisalimli I need data normalization

**Comment by kamilafsar** [comment]
For me, adding `import 'core-js/full/symbol/async-iterator';` at the top of my `index.js` worked. Thanks @elisalimli !
I didn't need to add Promise.allSettled, appears to be already available. I'm in a normal RN project, not expo.

**Comment by elisalimli** [comment]
@kamilafsar 

You're welcome! In my case, today I re-tried adding the pollyfill stuff to index.ts.Although that fixes the 'undefined is not a function' error, but again the same network error occurs. Do you use new expo-router with urql
> `[Network] Cannot convert undefined value to object at construct (native) at apply (native) at _construct (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:7125:28) at Wrapper (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:7087:25) at construct (native) at _createSuperInternal (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:128706:294) at call (native) at CombinedError (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:128742:26) at makeErrorResult (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:129002:31) at ?anon_0_ (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:129326:30) at throw (native) at resume (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:129380:30) at anonymous (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:129391:17) at tryCallOne (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16) at anonymous (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27) at apply (native) at anonymous (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:33521:26) at _callTimer (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:33440:17) at _callReactNativeMicrotasksPass (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:33470:17) at callReactNativeMicrotasks (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:33633:44) at __callReactNativeMicrotasks (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:6570:46) at anonymous (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:6382:45) at __guard (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:6554:15) at flushedQueue (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:6381:21) at callFunctionReturnFlushedQueue (http://192.168.100.7:19000/index.ts.bundle?platform=ios&dev=true&hot=false:6366:33)`

**Comment by hbriese** [comment]
> For me, adding `import 'core-js/full/symbol/async-iterator';` at the top of my `index.js` worked. Thanks @elisalimli ! I didn't need to add Promise.allSettled, appears to be already available. I'm in a normal RN project, not expo.
> 
> **Edit**: after adding `graphcache` with `@urql/storage-rn` I ended up doing:
> 
> ```
> import "core-js/full/symbol/async-iterator"
> import "core-js/full/promise/finally"
> ```

What version of expo? Was it with hermes or jsc?
I can't get it working with pollyfills using expo 48 hemes

**Comment by kitten** [comment]
If anyone would like to try this `wonka@6.3.3` contains a workaround that should allow React Native + Hermes's default Babel transpilations to still work with `fromAsyncIterable` & `toAsyncIterable`.

In other words, I believe, with the patch in `wonka`, this should now work without having to include the `symbol/async-iterator` polyfill from `core-js` manually.

https://github.com/0no-co/wonka/releases/tag/v6.3.3

**Comment by hbriese** [comment]
> If anyone would like to try this `wonka@6.3.3` contains a workaround that should allow React Native + Hermes's default Babel transpilations to still work with `fromAsyncIterable` & `toAsyncIterable`.
> 
> In other words, I believe, with the patch in `wonka`, this should now work without having to include the `symbol/async-iterator` polyfill from `core-js` manually.
> 
> https://github.com/0no-co/wonka/releases/tag/v6.3.3

Confirming that this indeed fixes the issue! :pray: 
Tested on react native 0.72 (expo 49)

**Comment by solominh** [comment]
just add wonka >=6.3.3 (yarn add wonka) => work
