### ISSUE TITLE
deduplication not working with `cache-and-network` after updating to latest urql

### ISSUE THREAD

**Issue by villesau** [urql-graphql/urql#3136]
### Describe the bug

We are seeing a lot of duplicate requests after updating to the latest urql which we don't see with older versions. We've removed the deprecated dedupe exchange. The exchange stack consists of these:

It seems to happen when the cache-policy is `cache-and-network`. Without that I'm not able to repro the issue.

### Reproduction

https://codesandbox.io/s/crazy-bird-qfcnpt?file=/src/index.js

E: Old version which works like expected: https://codesandbox.io/s/cool-fast-dczhs3?file=/src/index.js

### Urql version

urql 4.0.0, @urql/core 4.0.2

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

E: Some further discussion in Discord: https://discord.com/channels/1082378892523864074/1082386845553406002/threads/1096810324528746637

**Comment by kitten** [comment]
I'm still testing some edge cases, but if you'd like to look at the fix in your own app, you should be able to use the prerelease: `@urql/core@0.0.0-canary-20230418124333`
