### ISSUE TITLE
Missing example in next-urql documentation

### ISSUE THREAD

**Issue by torben3d** [urql-graphql/urql#3154]
### Describe the bug

Hello, 

While researching a ssr issue with `urql`, I came across `next-urql`.

I recognized the link to the mentioned example is broken. There is also no example in the mentioned folder structure.
https://github.com/urql-graphql/urql/tree/main/packages/next-urql#integration-with-_appjs

> Check out our example for using next-urql with _app.js [here](https://github.com/urql-graphql/urql/blob/main/packages/next-urql/examples/2-with-_app.js/README.md).

Note: the version mentioned below is the version of `next-urql` copied form `package.json`.

While exploring the repository a bit, I assume that is the correct link nowadays?

https://github.com/urql-graphql/urql/tree/main/examples/with-next

Thanks in advance
Best torben

### Reproduction

https://github.com/urql-graphql/urql/tree/main/packages/next-urql#integration-with-_appjs

### Urql version

5.0.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Hm, that readme should be out-of-date, so we should likely just delete it as it was never meant to be committed to the monorepo and is a leftover from when the repo was migrated into it.

**Comment by masterkain** [comment]
we can use some info how to use the lib with next.13 app dir 👍
