### ISSUE TITLE
Cached data bug after page navigation with next-urql + exchange-graphcache

### ISSUE THREAD

**Issue by dizlexik** [urql-graphql/urql#3160]
### Describe the bug

I've created a [reproduction](https://codesandbox.io/p/sandbox/condescending-resonance-pndq8r) of an issue where useQuery is returning data with __typename fields before page navigation and the same data without __typename fields after navigating. All cached data returned from useQuery after any navigation has occurred on the site is missing __typenames, which isn't a problem in itself since we would never rely on those values without explicitly including that field in the query, but what is having a negative effect is that the cached data coming out of useQuery does not match the previous data by reference. And this is true on every render so when any other component on a page fetches data that touches the cache it results in rerendering everything everywhere. This is bad for performance and also is breaking part of our application where we are feeding an array of objects out of useQuery into a table component which replaces rows when object references change, resulting in any row state (selected checkboxes in our case) being wiped out and replaced with default state.

Our workaround at the moment is to always include __typename in all of our queries. This makes Graphcache behave predictably across page navigation and cached data is always returned with the same references as previous results so things are working as expected/desired. Of course we would rather not have to include this unnecessary field in all of our queries, and there's now a chance that team members may forget to do this and introduce subtle bugs and performance issues. Ideally the results from useQuery would either always include __typename or never include it, and in either case references should always match previous results.

In troubleshooting this we came across a number of issues/PRs that were somewhat related to our issue here, but not exactly, and I couldn't find anything calling out page navigation in Next causing this strange change in how Graphcache behaves. Here are some links here for reference:  #1268 #1366 #2701 #2718

### Reproduction

https://codesandbox.io/p/sandbox/condescending-resonance-pndq8r

### Urql version

urql v4.0.0
@urql/exchange-graphcache v6.0.1
next-urql v5.0.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
I think this is likely related to the regression that made this change to this section of code necessary: https://github.com/urql-graphql/urql/blob/a6cc2884f939101963b8924126955d2e7a30a2cd/exchanges/graphcache/src/cacheExchange.ts#L201-L214

So, this may take a bit of time to untangle, but should be trivial for us to fix. Basically, I'm currently assuming that the issue here is that the original query document isn't being restored correctly

**Comment by dizlexik** [comment]
I see that the cache-and-network thing was resolved in [@urql/core v4.0.6](https://github.com/urql-graphql/urql/releases/tag/%40urql%2Fcore%404.0.6), and it's working again for me now 👍

**Comment by kitten** [comment]
Awesome! 🙌 Glad it's all working now. Refactoring some of Graphcache and Core to fix some regressions from the recent major releases did take two attempts in this case, but I hope it's worth it for you in the end ✌️
