### ISSUE TITLE
RFC(persisted-fetch): with `preferGetForPersistedQueries: true`, use POST when GET is not possible

### ISSUE THREAD

**Issue by NWRichmond** [urql-graphql/urql#3185]
## Summary

**Preamble**: I was initially going to file this as a bug, but am erring on the side of "the existing functionality was a design decision, so let's treat it as such and go the RFC route."

[`@urql/exchange-persisted`](https://github.com/urql-graphql/urql/tree/main/exchanges/persisted) has a `preferGetForPersistedQueries` option. When set to `true`, it [sets](https://github.com/urql-graphql/urql/blob/35c97ccca65470f25cc1295d78e18aaab4d2f6ef/exchanges/persisted/src/persistedExchange.ts#L166) the `preferGetMethod` [client option](https://formidable.com/open-source/urql/docs/api/core/#client) to `'force'`.

The `@urql/core` API docs note that in addition to `boolean` and `'force'`, `'within-url-limit'` is also an option for `preferGetMethod`.

With that in mind, the description for `preferGetMethod` reads:

> This is picked up by the `fetchExchange` and will force all queries (not mutations) to be sent using the HTTP GET method instead of POST if the length of the resulting URL doesn't exceed 2048 characters. When `'force'` is passed a GET request is always sent regardless of how long the resulting URL is.

The naming of `@urql/exchange-persisted`'s `preferGetForPersistedQueries` option sets an expectation that GET requests are "preferred," rather than "forced." In other words, I'd expect `preferGetForPersistedQueries: true` to send a GET request when possible (e.g. when the resulting URL doesn't exceed 2048 characters), but send POSTs when GETs are not possible. Unfortunately, APQ requests that exceed 2048 characters result in malformed GET requests instead of POSTs.

## Proposed Solution

In `@urql/exchange-persisted`, when `preferGetForPersistedQueries` is `true`, set the client's `preferGetMethod` setting to `'within-url-limit'`. This would allow for "graceful failure" of an excessively large APQ GET request by falling back to a POST request, which feels true to the semantics of a `preferGetForPersistedQueries` option.

## Requirements

1. When `@urql/exchange-persisted`'s `preferGetForPersistedQueries` setting is set to `true`, send a GET request if the request is 2048 characters or less.
2. When `@urql/exchange-persisted`'s `preferGetForPersistedQueries` setting is set to `true`, send a POST request if a GET request would exceed 2048 characters.

## Notes

I would be happy to create a minimal reproduction that demonstrates the issue. But since the current behavior is described explicitly in the docs, I suspect that a minimal reproduction isn't terribly valuable.

**Comment by kitten** [comment]
Yep, I can see that that's definitely not expected 👍

Regarding the proposed solution, my thinking currently is, it may be better to simply accept the same options on `preferGetForPersistedQueries` for now however, i.e. accept `boolean | 'force' | 'within-url-limit'`. This way we avoid the breaking change for now and also provide the same options and symmetry with what this does to the operation.

A reproduction is indeed not necessary 😅 It's a one line change after all. Let me know if you're interested in PR'ing this though. Also happy to take care of it myself, so let me know ✌️

**Comment by NWRichmond** [comment]
Thanks, @kitten! I'll draft up a PR within the next 72 hours.

**Comment by kitten** [comment]
Ah, you're right, I forgot about that 🤔 In this case, I suppose the only good option is indeed a breaking change. Given that `@urql/exchange-persisted` is quite “new” though, I suppose that’s not a problem at all. I think it should still use the string-like `'force' | 'within-url-limit'` literals as options though, since they’re just more descriptive, but other than that, I'm happy with any change you see fit :+1:

**Comment by NWRichmond** [comment]
Here's a first pass at a PR: https://github.com/urql-graphql/urql/pull/3192

I'm very open to feedback. Please let me know if you'd like to see any changes :)

**Comment by kitten** [comment]
Resolved and published as part of `@urql/exchange-persisted@4.0.0`
