### ISSUE TITLE
vue: Extra request with empty variables with computed isPaused

### ISSUE THREAD

**Issue by downace** [urql-graphql/urql#3215]
### Describe the bug

I can reproduce this issue with following conditions:

- Vue 3 + urql v4 (does not occur with v3),
- `persistedExchange` enabled,
- For `useQuery`: `pause` has common dependencies with `variables`.

When `pause` becomes `false`, extra request with empty variables is sent. Error like `Variable "$id" of required type "ID!" was not provided` can be seen in console.

```typescript
const variables = ref(null);

const { data } = useQuery({
  query: gql`
    query GetDragon($id: ID!) {
      dragon(id: $id) { id description }
    }
  `,
  variables,
  pause: computed(() => !variables.value),
});

setTimeout(() => {
  variables.value = { id: "5e9d058759b1ff74a7ad5f8f" };
}, 1000);
```

Correct request is also sent immediately, `error` is not populated, so extra request does not affect anything in app code.
I use `errorExchange` to catch the error and show it.

### Reproduction

https://codesandbox.io/p/sandbox/urql-exchange-persisted-v4-bug-5t8vbm?file=%2Fsrc%2FApp.vue%3A6%2C1-23%2C10

### Urql version

@urql/core v4.0.7
@urql/vue v1.1.1
@urql/exchange-persisted v4.0.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
@downace: Hiya 👋 Only coming around to this now, sorry for the delay!

Just to let you know. This doesn't have anything to do with the persisted queries. Instead, the main problem is that when `isPaused` and the request change at the same time, the source is changed twice. I wasn't aware that effects aren't batched more intuitively, but it's a simple fix

**Comment by downace** [comment]
Hi @kitten! Thanks for your response

> This doesn't have anything to do with the persisted queries

But the issue disappears if `persistedExchange` is removed from `main.ts` in reproduction sandbox.
Maybe there's something wrong with my reproduction, you can check it out yourself.
