### ISSUE TITLE
TS Error when trying to use the next-urql default exchanges

### ISSUE THREAD

**Issue by seanparmelee** [urql-graphql/urql#3219]
### Describe the bug

Hello! 👋 
I noticed the [Next.js](https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#nextjs) docs mentions:
> One added caveat is that these options may not include the exchanges option because next-urql injects the ssrExchange automatically at the right location. If you're setting up custom exchanges you'll need to instead provide them in the exchanges property of the returned client object.

I also see where this is [handled in the code](https://github.com/urql-graphql/urql/blob/1470a9c7474c75b65303b503c0a3a51e895f1a38/packages/next-urql/src/with-urql-client.ts#L111-L114). 

However, when I try to forgo passing `exchanges`:

```ts
export default withUrqlClient(() => ({
  url: 'http://localhost:3000/graphql',
}))(App);
```

I receive the following TS error: 

```
Property 'exchanges' is missing in type '{ url: string; }' but required in type 'ClientOptions'.ts(2741)
```

To reproduce this, please see the reproduction link. You'll need to open a terminal and run `yarn tsc` to see the error.

### Reproduction

https://codesandbox.io/s/vibrant-wozniak-7lhu9m

### Urql version

urql v4.0.2
next-urql 5.0.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
This option is now required, just like with `createClient`'s options and other similar APIs. We may not have caught all places in the docs that need changing since there's many mentioning the client options overall ✌️

**Comment by seanparmelee** [comment]
Thanks @kitten.

I'm happy to open a PR that corrects the docs. As for [the code that's currently defaulting the exchanges](https://github.com/urql-graphql/urql/blob/1470a9c7474c75b65303b503c0a3a51e895f1a38/packages/next-urql/src/with-urql-client.ts#L158-L161), I'm guessing that'll get removed in the next major release of `next-urql`?

**Comment by kitten** [comment]
@seanparmelee: I don't think a PR will be needed as the new PR should already be erasing this :v: I've marked it as resolving this issue
