### ISSUE TITLE
Add `reexecute()` to `@urql/svelte` (again!)

### ISSUE THREAD

**Issue by frederikhors** [urql-graphql/urql#3221]
## Summary

Upgrading from `@urql/svelte` 1 to 2 I missed `reexecute()` which is very useful sometimes when not using the reactive mode (`$:`) that Svelte offers.

## Proposed Solution

Can we re-add it, @jonathanstanley?

## Notes

It is been asked from other people too:

- @francois-blanchard: https://github.com/urql-graphql/urql/pull/2370#issuecomment-1153191285

- @rouzwelt: https://github.com/urql-graphql/urql/pull/2370#issuecomment-1172977813

(BTW: did you find an alternative way?)

**Comment by rouzwelt** [comment]
> ## Summary
> 
> Upgrading from `@urql/svelte` 1 to 2 I missed `reexecute()` which is very useful sometimes when not using the reactive mode (`$:`) that Svelte offers.
> 
> ## Proposed Solution
> 
> Can we re-add it, @jonathanstanley?
> 
> ## Notes
> 
> It is been asked from other people too:
> 
> - @francois-blanchard: https://github.com/urql-graphql/urql/pull/2370#issuecomment-1153191285
> 
> - @rouzwelt: https://github.com/urql-graphql/urql/pull/2370#issuecomment-1172977813
> 
> (BTW: did you find an alternative way?)

I figured out a workaround using svelte reactive block

**Comment by frederikhors** [comment]
> I figured out a workaround using svelte reactive block

Thanks, can you show us?

**Comment by rouzwelt** [comment]
> > I figured out a workaround using svelte reactive block
> 
> Thanks, can you show us?

sure, take a look here:
https://github.com/rainprotocol/rain-toolkit-gui/blob/304e6b49d4d365f0a358f9bad6c46a485d927213/src/routes/sale/SaleChart.svelte#L65

the `refresh()` method is responsible for performing a similar thing to `reexecute()`, which is bound to a spinning arrow button on html.

a few lines higher you can see the query is also bound to a svelte reactive variable.
Hope it helps, let me know if you have any questions

**Comment by kitten** [comment]
The docs state another method: https://formidable.com/open-source/urql/docs/basics/svelte/#reexecuting-queries

And there's also options to reassign the original store, so I'm not sure there's anything here that warrants implementing unless:
- the docs' proposed solution outright doesn't work
  - (in case a docs change isn't enough)
- there's a special edge case that's uncovered
- something's changed in Svelte that makes this necessary

**Comment by frederikhors** [comment]
Thanks for the answer, @kitten.

In Svelte is very frequent to have code like:

```svelte
<script lang="ts">
  import { queryStore, gql, getContextClient } from '@urql/svelte';

  export let condition;
  export let pagination;
  export let orderBy;
  export let canBeVisible;

  const client = getContextClient();
  const query = gql`
    query {
      todos {
        id
        title
      }
    }
  `

  $: todos = queryStore({
    client,
    query,
    variables: {
      input: {
        pagination,
        condition: {
          ...condition,
          player: { name: true },
          show_team: { name: true },
        },
        orderBy,
      }
    },
    pause: !canBeVisible,
  });
</script>
```

### First issue

The code you propose in docs:

```ts
function refresh() {
  queryStore({
    client,
    query,
    requestPolicy: 'network-only'
  });
}
```

forces us to repeat many of the instructions already contained in `$: todos...` (e.g.: `pause`, `variables` and we should make them $: reactive too).

### Second issue

Sometimes we need to be really fast in coding and we would like to avoid writing a custom `refresh()` function if we can (even in templates) call directly:

```svelte
<button on:click={() => todos.reexecute()}>Refresh results</button>
```

### Proposal

It would be amazing to have a `reexecute()` method to use, such as:

```ts
$: todos = queryStore({
  client,
  query,
  //...
});

// So I can use anywhere:
todos.reexecute()
```

**Comment by patsissons** [comment]
ran into the mimssing `reexecute()` tonight, here is a relatively svelte-y reactive workaround. hope this is helpful for others.

```ts
// $lib/queries.ts

import {
  type AnyVariables,
  getContextClient,
  gql,
  type QueryArgs,
  queryStore,
  type OperationResultState,
} from '@urql/svelte'
import { derived, writable } from 'svelte/store'

function withPolling<Data = unknown, Variables extends AnyVariables = AnyVariables>(
  queryArgs: QueryArgs<Data, Variables>,
) {
  const result = writable<OperationResultState<Data, Variables>>()

  return {
    refresh,
    poll,
    ...derived([queryStore(queryArgs), result], ([initial, next]) => {
      return next || initial
    }),
  }

  function refresh() {
    return queryStore<Data, Variables>({ ...queryArgs, requestPolicy: 'network-only' }).subscribe(
      result.set,
    )
  }

  function poll(intervalMs = 5_000) {
    const timeout = setInterval(refresh, intervalMs)

    return () => {
      clearInterval(timeout)
    }
  }
}

export function queryTodos() {
  return withPolling({
    client: getContextClient(),
    query: gql`
      query {
        todos {
          id
          title
        }
      }
    `,
  })
}
```

```svelte

<script lang="ts">
  import { onDestroy } from 'svelte'
  import { queryTodos } from '$lib/queries'

  const query = queryTodos()
  const dispose = query.poll()

  $: todos = $query.data?.todos

  onDestroy(dispose)

  function refresh() {
    // this will update todos above
    query.refresh()
  }
</script>

<pre>{JSON.stringify(todos)}</pre>
```
