### ISSUE TITLE
graphcache: Untranspiled class property initializers break Safari <14.1

### ISSUE THREAD

**Issue by mattwoodage** [urql-graphql/urql#3274]
### Describe the bug

Since switching from urql/core 3.0.3 to 4.0.10 and graphcache 5.0.1 to 6.1.1 our Next bundle no longer runs in Safari 12 or 13.

<img width="1048" alt="Screenshot 2023-06-14 at 17 27 57" src="https://github.com/urql-graphql/urql/assets/1794057/1f35aa93-578f-4c7d-958e-dd6b8b60bf02">

It's due to the public field declaration use in GraphCache - specifically the lines
`keyOfField=keyOfField;`
and
`resolveFieldByKey=this.resolve;` 
in class Store

I can see you changed browser support in August 2022 - and say that you support ECMA2015+ which includes Safari 12.

The addition of `@babel/plugin-proposal-class-properties` would correct the transpilation I believe.  

Is this something you'd be happy to add please?

Using https://babeljs.io/ - compiled version of urql-exchange-graphcache.mjs - AS IS:
<img width="708" alt="Screenshot 2023-06-15 at 10 28 06" src="https://github.com/urql-graphql/urql/assets/1794057/9678ccd2-d687-4021-af85-29a4934fbd7a">

Using https://babeljs.io/ - compiled version of urql-exchange-graphcache.mjs - WITH @babel/plugin-proposal-class-properties PLUGIN:

<img width="637" alt="Screenshot 2023-06-15 at 10 28 27" src="https://github.com/urql-graphql/urql/assets/1794057/ad3568fd-d67a-40e0-9ec0-355b50c566d0">

### Reproduction

https://github.com/urql-graphql/urql/blob/main/exchanges/graphcache/src/store/store.ts

### Urql version

    "@urql/core": "^4.0.10",
    "@urql/exchange-graphcache": "^6.1.1",

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Hey, thanks for reporting this! 🙌 
I'll make sure I get a hotfix out since this affects Safar <14.1 and is hence quite severe. I spotted the PR that regressed this but, to keep the build process simple and lean with recent changes, I put a further ESLint rule in place that should prevent regression on this.

Cheers!

**Comment by mattwoodage** [comment]
@kitten  thanks so much.
