### ISSUE TITLE
persistedExchange duplicates operations

### ISSUE THREAD

**Issue by geekuillaume** [urql-graphql/urql#3311]
### Describe the bug

Enabling the new persisted exchange breaks the queries deduplication. This happens both when the persisted query is already registered on the server and also when the query is not yet registered and the server returns a `PersistedQueryNotFound` error.

### Reproduction

https://codesandbox.io/s/urql-persisted-exchange-query-duplication-bug-repro-hnfjyr

### Urql version

urql@4.0.4
@urql/exchange-persisted@4.0.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by geekuillaume** [comment]
@kitten thanks for this incredible response time :) Urql is awesome and we're using it extensively at Vizcom. We're super happy to give a little back to the community and you for your awesome work!

**Comment by kitten** [comment]
@geekuillaume That's kind and awesome of you! ❤️ I'm glad you're happy and I'm sorry if this regression caused you any trouble. I'm not sure how I missed this during the refactor
