### ISSUE TITLE
Cache first queries that error execute twice in suspense mode

### ISSUE THREAD

**Issue by zenios** [urql-graphql/urql#3347]
### Describe the bug

When a cache-first query fails and we are using suspense the query is executed twice.

I am not sure if this is actually a bug or the same behaviour as network-only since error queries are not cached so please close it if not.

### Reproduction

https://codesandbox.io/p/sandbox/crazy-roman-86cdyn

### Urql version

urql v4.0.5

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
This is expected, yes. Since errors aren't cached, once the component remounts the request is executed again on mount
