### ISSUE TITLE
graphcache: Extra variables missing in updates

### ISSUE THREAD

**Issue by Undistraction** [urql-graphql/urql#3355]
### Describe the bug

I've just upgraded URQL to the latest packages, and I'm no longer receiving the extra arguments ([documentation](https://formidable.com/open-source/urql/docs/graphcache/cache-updates/#variables-for-optimistic-updates)) that I pass in to a mutation in the Graphcache's `updates`. The arguments used by the query are still present, but the additional arguments are not. 

Mutation:
```
const [, deleteLike] = useMutation(DeleteLikeMutation)
...
deleteLike({id, enrolmentId})
```

Relevant graphcache config:
```
updates: {
    Mutation: {
       deleteLike(
          result,
          { id },
          cache,
          { variables: { enrolmentId } }
        ) {
           // id is present
           // enrolmentId is not present (no key or value)
        }
      }
   }
```

Using the map exchange I have confirmed that the additional variable is present on the operation before it reaches the graphcache-exchange. I've also added some logging and confirmed that the variable is present when it is first processed by the graphcache-exchange. 

### Reproduction

To follow

### Urql version

```
@urql/exchange-retry@^1.2.0
@urql/exchange-graphcache@^6.3.1
@urql/exchange-auth@^2.1.6
@urql/core@4.1.1
urql@4.0.5
```

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by Undistraction** [comment]
Looks like [the problem is here](https://github.com/urql-graphql/urql/blob/344b54410aaaf3927c70174ad8e810ccceff336d/exchanges/graphcache/src/operations/write.ts#L111). `request.variables` is used  to `makeContext`, which only comprises of the variables that were used in executing mutation, not the additional variables that were passed to `useMutation` which [get stripped here](https://github.com/urql-graphql/urql/blob/344b54410aaaf3927c70174ad8e810ccceff336d/exchanges/graphcache/src/cacheExchange.ts#L167).

**Comment by kitten** [comment]
Yes, extra variables are always present before an operation is sent onwards to the exchange that'll send it to the API. However, after forwarding these variables will be filtered.
The code you link unfortunately has no relation to this. The `operation` variable there isn't an `Operation` type of `@urql/core` bit is rather an `OperationDefinitionNode`.

We're probably missing an `operations.get` call however to retrieve the prior operation with unchanged variables. I'll have to check this out more closely though, since there's been a few additional changes since this was introduced

**Comment by Undistraction** [comment]
@kitten yeah. Sorry. Deleted that update as I realised I'd gone down the wrong path. I have confirmed that:
- Operation arrives in the exchange with all variables present. 
- By the time `writeSelection` is called (from `updateCacheWithResult`), the operation has been mutated (compared the keys) and the additional variables are no longer present.

**Comment by Undistraction** [comment]
In case it's useful, here are the upgrades that caused the issue. Don't have time to drill into which one particularly now as I've just had to roll them back for the moment. 
```
@urql/exchange-retry@^1.2.0 No change
@urql/exchange-graphcache 6.1.4 => 6.3.1
@urql/exchange-auth 2.14 => 2.1.6
@urql/core 4.0.10 => 4.1.1
urql 4.04 => 4.0.5
```
