### ISSUE TITLE
null data has been returned after fetch done with valid data when using nested local resolver

### ISSUE THREAD

**Issue by jet2jet** [urql-graphql/urql#3370]
### Describe the bug

When using nested local resolver (resolver not under root `Query`), returned data may be `null` even though data has been fetched correctly.

If I changed the line below:

https://github.com/urql-graphql/urql/blob/%40urql/exchange-graphcache%406.3.2/exchanges/graphcache/src/operations/query.ts#L612

```diff
-  } else if (!isOwnedData && prevData === null) {
+  } else if (isOwnedData && prevData === null) {
```

... it seems to work correctly.  
\# I saw that in commit 6031d913732f5e480cdbc2e3c2c537dc7e5d6d42 `skipNull` was changed to `isOwnedData`, but in the only above line `!` was added.

### Reproduction

https://github.com/jet2jet/urql-local-resolver-test

1. Run `npm run start`
2. Open http://localhost:3000
3. When Todo list is displayed, type Todo id to `ID` field and press `Get`
4. Expect behavior: Todo detail data is retrieved and displayed
5. Actual behavior: `Todo is null...` is displayed

### Urql version

urql v4.0.5
@urql/exchange-graphcache v6.3.2

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
That's a really nice catch and a great diagnosis! I've confirmed that the line you mentioned contains a typo (which is more easily spotted when comparing it to `resolveLink`) and wrote a quick unit test next to the one that checks that `resolveLink` behaves correctly, to prevent this from regressing again. Cheers! ❤️
