### ISSUE TITLE
persistedExchange(APQ) doesn't work with cacheExchange due to Document Caching

### ISSUE THREAD

**Issue by soleo** [urql-graphql/urql#3417]
### Describe the bug

with the following setup for Client
```
const client = new Client({
  url: 'https://trygql.formidable.dev/graphql/apq-weather',
  exchanges: [
    cacheExchange,
    persistedExchange({
      preferGetForPersistedQueries: true,
    }),
    fetchExchange,
  ],
});
```
It would always hit the documentCache for tries.

### Reproduction

https://github.com/soleo/urql/tree/bug/apq-with-cache/examples/with-apq-cache

### Urql version

@urql/exchange-persisted 4.1.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
I'm not sure what you mean by
> It would always hit the documentCache for tries.
It's expected for a query operation to be checked against the configured cache exchange, depending on the request policy that's used

**Comment by soleo** [comment]
https://github.com/urql-graphql/urql/discussions/3281 Got answers from the discussion there. We can close this issue. It is probably me not using requestPolicy correctly here.
