### ISSUE TITLE
storage missing in typed graphcache

### ISSUE THREAD

**Issue by villesau** [urql-graphql/urql#3455]
### Describe the bug

When updating to latest urql and codegenerators, I'm getting following type-error:

```
src/client/graphql/client.ts:78:37 - error TS2345: Argument of type '{ keys: { ...: () => null; }; updates: { Mutation: { ...: (result: { ...: WithTypename<ReviewRequest>[]; }, args: ..., cache: Cache) => void; ... 25 more ...; ......' is not assignable to parameter of type 'GraphCacheConfig'.
  Property 'storage' is missing in type '{ keys: { ... }; updates: { Mutation: { ...: (result: { ...: WithTypename<ReviewRequest>[]; }, args: ..., cache: Cache) => void; ... 25 more ...; ...' but required in type 'OfflineExchangeOpts'.

 78     cacheExchange<GraphCacheConfig>({
                                        ~
 79       keys: {
    ~~~~~~~~~~~~~
... 
435       },
    ~~~~~~~~
436     }),
    ~~~~~

  node_modules/@urql/exchange-graphcache/dist/urql-exchange-graphcache.d.ts:115:5
    115     storage: StorageAdapter;
            ~~~~~~~
    'storage' is declared here.

```

Is storage now needed or is the type-error a bug?

### Reproduction

-

### Urql version

    "urql": "^4.0.6",  
    "@urql/devtools": "^2.0.3",
    "@urql/exchange-auth": "^2.1.6",
    "@urql/exchange-graphcache": "^6.4.0",
    "@urql/exchange-retry": "^1.2.0",
    
Versions without issues:
    
    "urql": "^4.0.2",
    "@urql/devtools": "^2.0.3",
    "@urql/exchange-auth": "^2.1.2",
    "@urql/exchange-graphcache": "^6.0.4",
    "@urql/exchange-retry": "^1.2.0",

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
That's a bug in latest graphcache codegen, have a PR open there but not much luck 😅

**Comment by villesau** [comment]
I did everything within my power to move it forward and 👍ed the PR! Thanks for the workaround!

**Comment by JoviDeCroock** [comment]
Updated my PR going to close this out as it's not in our power
