### ISSUE TITLE
Possible memory leak when using multiple queries on the same page

### ISSUE THREAD

**Issue by juusopiikkila** [urql-graphql/urql#3507]
### Describe the bug

When using two queries on the same page and the other one is awaited and the other one is not and that one is using data from the awaited query, there is a memory leak. 

Using the reproduction memory usage climbs from ~40 Mb up to ~800 Mb (autocannon with 60 sec duration and 10 connections) and it never comes down.

### Reproduction

https://github.com/juusopiikkila/nuxt-urql-memory-leak

### Urql version

@urql/vue v1.1.2

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Just to clarify before looking into this because that's an important distinction: Does it never come down and stay stuck at 800MB (I assume MB not Mb?) or does it crash?

If your server doesn't actually rise in usage and/or crash it's not a leak, so just clarifying here.

Also just to point this out, there isn't anything special going on here. If you have just two operations (ie two document + variables combos) then it's more of a question how many concurrent queries are actually run as no memory is retained in the core client, bindings, or exchanges 🤔

**Comment by juusopiikkila** [comment]
Yeah sorry I meant MB. I tested it again and when the test was completed memory usage was at ~800MB and then it slightly decreased to ~700MB. No crashes, still works fine at that point when manually checking with browser. Memory usage just stays at ~700MB while I waited for 10 minutes for it to come down.

**Comment by kitten** [comment]
Hm, ok gotcha 👍 That doesn't necessarily sound like a memory leak, but a Chrome debugger memory snapshot could show you what's being retained and what's using that memory.

Generally, it's possible that a combination of GraphQL result data and Vue app tree data is being retained concurrently. But it's hard to tell how much memory that adds up to. Generally, 800MB could be plausible given that the GC may choose to also not activate an aggressive sweep phase when it still has enough heap space left

**Comment by juusopiikkila** [comment]
Ok I've now updated the reproduction repo with clearer tests. It wasn't even about using the data from the first query in the second, it leaks with just two awaited queries. With just one query there isn't any leak. Also I added a mock API endpoint under the api routes so that the external service isn't affecting the results. 

I also set max_old_space_size to 512MB to see if it changed anything.

Below are the results from the autocannon tests. I'm not that good at decyphering the snapshots yet so that doesn't help me much. Those memory readings are taken from the Chrome debuggers memory view after each test.

```
# /no-leak

11k requests in 60.04s, 17 MB read
Memory usage: 23.8 MB

# /leak

9k requests in 60.04s, 13.2 MB read
Memory usage: 1201 MB
```

**Comment by kitten** [comment]
Gotcha! That's awesome. I'll have a look at the memory debugger myself this evening. Typically, I'd assume we've created some kind of promise chain or cycle here 🤔

**Comment by Bcavez** [comment]
I can confirm we have the same issue on our project. 
Using @urql/vue v1.1.2 with nuxt 3.

Any page/component which has two queries will retain all the setup context of the component in memory and it is never released.
![image](https://github.com/urql-graphql/urql/assets/52085295/83b7dd09-4926-463f-bbd7-1a70ae4dc9b5)
![image](https://github.com/urql-graphql/urql/assets/52085295/6bf19542-bba9-4faa-b5ec-dc2dcc24697d)
![image](https://github.com/urql-graphql/urql/assets/52085295/d3a282a8-350a-4229-969d-361530efb7b5)

For a while I thought it was not an issue with urql as it is not just urql objects like graphcache, queries and data that are retained but also other objects like router object, unhead object etc... Basically anything in the setup function.

But if I remove the second query, it always fixes the problem, on all of the pages/components.

@kitten Have you had a chance to look at this issue yet ?

**Comment by JoviDeCroock** [comment]
@negezor are you by any chance initializing your `graphCache` globally? If so you might want to move that to your boostrapping code so that it can be garbage collected when your SSR completes.

**Comment by negezor** [comment]
@JoviDeCroock no. I have a new instance of the application initialized for each request. Including graphcache, otherwise the same data would be sent for each user and it would be a data access violation.

**Comment by negezor** [comment]
After investigating further, I seem to have some ideas about why the memory leak is happening. For some reason, the request object, which is not being mutated on my end, has a large number of ReactiveEffect.
![Screenshot 2024-06-18 040625](https://github.com/urql-graphql/urql/assets/9392723/fea76c11-48bd-4c76-b9b4-e8c19c5b6850)

Apparently, this is happening here.
https://github.com/urql-graphql/urql/blob/118d74b238007264cacfb91fc12de74370d5766e/packages/vue-urql/src/useQuery.ts#L248

**Comment by yurks** [comment]
@negezor, https://github.com/urql-graphql/urql/pull/3612 completely breaks reactivity support for variables, like `{ variables: { somevar: ref('value') }}`, as `reactive()` unwraps all nested reactive props

**Comment by yurks** [comment]
@JoviDeCroock @negezor
this issue should be resolves in https://github.com/urql-graphql/urql/pull/3619 without side-effects

**Comment by Warxcell** [comment]
I have consistent memory leak, but I don't know where from. Memory raises from 300MB to 4.5GB (which is maximum of the server itself) and then crashes with OOM error. Waiting for release to test if leak was coming from here. :)

**Comment by Warxcell** [comment]
Confirmed. After upgrading to [1.4.0-canary-068df71f](https://www.npmjs.com/package/@urql/vue/v/1.4.0-canary-068df71f) - how memory stays at 200MB.
