### ISSUE TITLE
Non RSC authExchange failing

### ISSUE THREAD

**Issue by Nohac** [urql-graphql/urql#3525]
### Describe the bug

I've followed the steps for nextjs appdir. I've added `authExchange` to the non RSC setup, and in `addAuthToOperation` I'm fetching access token from the server using nextjs server action. When I do this, I'm getting the following errors/warnings:
```
Warning: Can't perform a React state update on a component that hasn't mounted yet. This indicates that you have a side-effect in your render function that asynchronously later calls tries to update the component. Move this work to useEffect instead.
Router@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:90:130
ErrorBoundaryHandler@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:62:9
ErrorBoundary@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:87:56
AppRouter@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:374:48
ServerRoot@webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:154:25
RSCComponent
Root@webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:171:25 [app-index.js:32:21](webpack://_N_E/node_modules/next/dist/client/app-index.js?d705)
```
```
authExchange()’s initialization function has failed, which is unexpected.
If your initialization function is expected to throw/reject, catch this error and handle it explicitly.
Unless this error is handled it’ll be passed onto any `OperationResult` instantly and authExchange() will block further operations and retry. Error: Connection closed.
```

### Reproduction

https://stackblitz.com/edit/github-1sqstp?file=app%2Fnon-rsc%2Flayout.tsx

### Urql version

urql 4.0.6

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
I don't think you should be able to call server-actions from non-DOM interactions 😅 as what seems to basically be happening is that the connection is closed immediately.

**Comment by Nohac** [comment]
You're right. I was following [this guide](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#non-form-elements) and it looked like I could use server actions like a normal async function.

Moving from action to a normal api for subsequent fetches, and passing the token from RSC to the provider on initial render made the issues go away.
