### ISSUE TITLE
Invalidating cache in Graphcache doesn't trigger query refetch in Next.js app router

### ISSUE THREAD

**Issue by ookil** [urql-graphql/urql#3527]
### Describe the bug

When using Graphcache with Next.js and app router (with client components) there seems to be an issue that after invalidating cache queries are not refetched and stale data is shown. 
This was not an issue with pages but stopped working when migrating to app router.
I created a reproduction that shows the issue. Only after refetching the query with `{ requestPolicy: "network-only" }` fresh data is shown.

### Reproduction

https://github.com/ookil/urql-graphcache

### Urql version

"@urql/core": "^4.3.0",
"@urql/exchange-graphcache": "^6.5.0",
"@urql/next": "^1.1.1",

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
This seems to be because [this check](https://github.com/urql-graphql/urql/blob/main/packages/core/src/exchanges/ssr.ts#L216-L219) evaluates to false.

When I add

```ts
const ssr = ssrExchange({
  isClient: typeof window !== 'undefined'
});
```

This works correctly

**Comment by ookil** [comment]
@JoviDeCroock thanks a lot!
