### ISSUE TITLE
Introspected schema from urql-introspection doesn't match type of exchange-graphcache

### ISSUE THREAD

**Issue by imcvampire** [urql-graphql/urql#3537]
### Describe the bug

```
                Type 'OperationInstance' is not assignable to type 'OperationInstance | undefined'.
                  Type 'import("/.../node_modules/.pnpm/@urql+core@4.2.0_graphql@16.8.1/node_modules/@urql/core/dist/urql-core-chunk").OperationInstance' is not assignable to type 'import("/.../node_modules/.pnpm/@urql+core@4.3.0_graphql@16.8.1/node_modules/@urql/core/dist/urql-core-chunk").OperationInstance'.
                    Type 'OperationInstance' is not assignable to type '{ readonly _opaque: unique symbol; }'.
                      Types of property '_opaque' are incompatible.
                        Type 'typeof _opaque' is not assignable to type 'typeof _opaque'. Two different types with this name exist, but they are unrelated.

12       cacheExchange({
         ~~~~~~~~~~~~~~~
13         schema: introspectedSchema,
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14       }),
   ~~~~~~~~
 ```

### Reproduction

- Install latest version of @urql/exchange-graphcache and @graphql-codegen/urql-introspection

### Urql version

urql: 4.0.6
@urql/exchange-graphcache: 6.5.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
You've got a duplicated installation of `@urql-core`, namely `4.2.0` and `4.3.0`

Seeing that you're using `pnpm`, this can either be resolved by running `pnpm dedupe`, by manually editing the lockfile, or by manually installing a newer one and ensuring that `pnpm` has replaced the two old versions with just one.
