### ISSUE TITLE
Invalidate with a key does not produce expected result

### ISSUE THREAD

**Issue by BickelLukas** [urql-graphql/urql#3543]
### Describe the bug

The documentation says that for the "entity" parameter it can be a GraphQL object or an entity key:
<img width="432" alt="image" src="https://github.com/urql-graphql/urql/assets/16354178/89901749-17b1-45e3-89a8-f0c8b474cb32">

but calling `cache.invalidate("123")` does not work as expected.

The problem is the `shouldInvalidateType` check when trying to invalidate just a single entity without fields or args
https://github.com/urql-graphql/urql/blob/431b64b4086d3d1dafb2af4881a95fa642134daf/exchanges/graphcache/src/store/store.ts#L167-L171

because of this it is now trying to invalidate the type "123" instead of the entity with id "123"

### Reproduction

In Description

### Urql version

urql: 4.0.6
@urql/exchange-graphcache: 6.5.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
This is fixed and released with #3544

**Comment by BickelLukas** [comment]
Works perfectly now. Thanks for the amazingly quick fix and release! 🎉
