### ISSUE TITLE
Multiple requests when using react suspense

### ISSUE THREAD

**Issue by danielkaxis** [urql-graphql/urql#3565]
### Describe the bug

The bug is that urql is somehow spamming multiple requests.
Our application works like this basically. It has a set of modules and we iterate them returning lazy loaded components wrapped in React Suspense.

```
<Suspense>
  modules.map((m) => {
    component = lazy(m.component)
    return <Route 
      ...
    />
  })
</Suspense>
```

We don't know why this happens. But we suspect that it has something to do with how we structured one of our tree. We also suspect it has something to do with the lazy loading and react suspense In the example we have been able to reproduce the issue.

Consider this structure. It only happens when it is like this.
```
Query
  vehicles
Vehicles
  car
  cars
  bicycle
  bicycles
```

### Reproduction
https://github.com/danielkaxis/urqlsuspensetest/tree/multiplerequests

__mocked_generated__ folder has the schema and urql resolvers.

yarn
yarn serve
localhost:8000
Open developer tools
reload page

All logs show the query that has been called with console.count().
`Car:name` should be called 4 times but is called 14 times.

Why is it called so many times?

![image](https://github.com/urql-graphql/urql/assets/77433590/81f37e8e-678b-4c03-a38b-69eab378d4f7)

Comment out the mutation in App.tsx line 13.
```js
await client.mutation(userMutation, {}).toPromise()
```
reload the page
`Car:name` is now called only 8 times.

Why did that decrease the number of requests?

### Urql version

```
"@graphql-tools/schema": "10.0.3",
"@urql/devtools": "2.0.3",
"@urql/exchange-execute": "2.2.2",
"@urql/exchange-graphcache": "7.0.1",
"graphql": "16.8.1",
"urql": "4.0.7",
```

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
Hey,

It's really unclear what you are expecting to happen here or how we would observe the issue. I would encourage you to give us clear reproduction/observation steps and upgrade your urql dependencies.

**Comment by danielkaxis** [comment]
Hey @JoviDeCroock,

Thanks for your reply. I have now updated the example and intructions.
Thanks for the tip about the logger API. I will check that out.

**Comment by ericclemmons** [comment]
Hey @danielkaxis, thanks for opening this issue.  I'll have to check into this as well because I just ran across this same problem when using `React.lazy` – `useQuery` underneath it doesn't seem to keep the Suspense boundary in a loading state 🤔

**Comment by HitomiWin** [comment]
Hey,
I have tried to console log the issues with the logger function.
It looks that queries once called are not cached ??? 🤔 
![urql](https://github.com/urql-graphql/urql/assets/78015767/72929d9c-e78d-499e-9e7d-8d48ce73b029)

**Comment by JoviDeCroock** [comment]
As I've said before, it's quite hard to deduct what's going on in your reproduction. I'll try to spend some time on this over the next week, something that could go a long way would be for you to check whether it helps to 

- Hoist client creation to the global scope (as it stands you do `initClient` in a `Suspense` tree without memo/... which is dangerous in and of itself)
- Identify at what version this started happening

**Comment by danielkaxis** [comment]
> As I've said before, it's quite hard to deduct what's going on in your reproduction. I'll try to spend some time on this over the next week, something that could go a long way would be for you to check whether it helps to
> 
> * Hoist client creation to the global scope (as it stands you do `initClient` in a `Suspense` tree without memo/... which is dangerous in and of itself)
> * Identify at what version this started happening

Sorry if my new example is also unclear. I really really tried :crying_cat_face:  I'm not sure how I can explain it better. Thanks for the tip. I will try it.

**Comment by JoviDeCroock** [comment]
It is def weird that it's being re-queried, it almost feels like GraphCache is just removing data. This might just come down to layers and the mutation layer skewing here 😅 mainly because all operations are in-flight at the same time.

Currently don't have time to debug this but ye, might be something in there

**Comment by danielkaxis** [comment]
> It is def weird that it's being re-queried, it almost feels like GraphCache is just removing data. This might just come down to layers and the mutation layer skewing here 😅 mainly because all operations are in-flight at the same time.
> 
> Currently don't have time to debug this but ye, might be something in there. Your thesis is correct though that this produces multiple requests, when using the `debugExchange` I can clearly see that every request is duplicated.
> 
> Update after spending the evening on this, the offending lines are situated [here](https://github.com/urql-graphql/urql/blob/main/packages/core/src/client.ts#L695-L708). Basically we _should_ change this up to check whether it's not queued and whether the dispatched does not contain it yet like:
> 
> ```js
> if (!queued && (!dispatched.has(operation.key) || operation.context.requestPolicy === 'network-only')) {
>   queue.push(operation);
>   Promise.resolve().then(dispatchOperation);
> } else {
>   dispatched.delete(operation.key);
>   Promise.resolve().then(dispatchOperation);
> }
> ```
> 
> That however re-introduces the issue we faced in #3254 where we do an optimistic mutation which results in the `dispatch` and when the response comes in the updater results in a second `dispatch` this second one does not go throug has the optimistic reexecute is seen as `dispatched`. Will need some more time on this but thought I'd update this issue already 😅

Wow! This is amazing news. I can try to test this locally and see if the issue goes away :)

**Comment by danielkaxis** [comment]
> > It is def weird that it's being re-queried, it almost feels like GraphCache is just removing data. This might just come down to layers and the mutation layer skewing here 😅 mainly because all operations are in-flight at the same time.
> > Currently don't have time to debug this but ye, might be something in there. Your thesis is correct though that this produces multiple requests, when using the `debugExchange` I can clearly see that every request is duplicated.
> > Update after spending the evening on this, the offending lines are situated [here](https://github.com/urql-graphql/urql/blob/main/packages/core/src/client.ts#L695-L708). Basically we _should_ change this up to check whether it's not queued and whether the dispatched does not contain it yet like:
> > ```js
> > if (!queued && (!dispatched.has(operation.key) || operation.context.requestPolicy === 'network-only')) {
> >   queue.push(operation);
> >   Promise.resolve().then(dispatchOperation);
> > } else {
> >   dispatched.delete(operation.key);
> >   Promise.resolve().then(dispatchOperation);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That however re-introduces the issue we faced in #3254 where we do an optimistic mutation which results in the `dispatch` and when the response comes in the updater results in a second `dispatch` this second one does not go throug has the optimistic reexecute is seen as `dispatched`. Will need some more time on this but thought I'd update this issue already 😅
> 
> Wow! This is amazing news. I can try to test this locally and see if the issue goes away :)

EDIT: On a side note, hoisting init of urql did not help.

**Comment by danielkaxis** [comment]
Thanks @JoviDeCroock! We will upgrade our packages and make sure it works. Much appreciated.

**Comment by JoviDeCroock** [comment]
I have been trying to make this work as good as I can but ultimately this is not really a structure we want to encourage, you can ofcourse make it work with an exchange that does the [deduping for you](https://github.com/urql-graphql/urql/blob/%40urql/core%403.2.2/packages/core/src/exchanges/dedup.ts).

The pattern here is a bit counter to GraphQL where you are creating a lot of requests throughout your application that are inter-dependent rather than one big selection-set.

**Comment by danielkaxis** [comment]
I want to post an updated example project for anyone interested in the outcome of this issue.
https://github.com/danielkaxis/urqlsuspensetest/tree/multiplerequestsresolution

I removed the additional query document for fetching **_a single_** car. I now only have one document fetching all cars. 
The schema is still as before.
```
// Schema
Query
  vehicle
  
Vehicle
  car
  cars
  
Car
  name

// Query
export const VehiclesDocument = gql`
  query {
    vehicle {
      cars {
        id
        name
      }
    }
  }
`
```

To demonstrate: 
In Vehicles.tsx I query VehiclesDocument.
https://github.com/danielkaxis/urqlsuspensetest/blob/multiplerequestsresolution/src/components/Vehicles.tsx

In Car.tsx I also query VehiclesDocument
https://github.com/danielkaxis/urqlsuspensetest/blob/multiplerequestsresolution/src/components/Car.tsx

**_I have 4 cars_**
I also see them called **_only 4 times_** :smile: 
![image](https://github.com/urql-graphql/urql/assets/77433590/941ae062-a03f-4dd0-9d41-514273b962b0)
