### ISSUE TITLE
(vue) useQuery pause does not update when passing a ref

### ISSUE THREAD

**Issue by arkandias** [urql-graphql/urql#3594]
### Describe the bug

According to the doc, we can pass a reactive `pause` input to `useQuery`. Yet, the pause status of the query does not update when the reference's value changes. I have linked a StackBlitz with the following example from the doc:
```
const skip = ref(0);
    const shouldPause = ref(true);

    const pokemons = await useQuery({
      query: gql`
        query ($skip: Int!) {
          pokemons(limit: 10, skip: $skip) {
            id
            name
          }
        }
      `,
      variables: { skip },
      pause: shouldPause,
    });
```
You can see that the query stays on pause (it does not fetch and the property `isPaused` is indeed staying to `true`) even when `shouldPause`'s value is switched to `false`. On the other hand, if you start with `const shouldPause = ref(true);`, then the query never pauses.

### Reproduction

https://stackblitz.com/edit/github-uroxw1?file=src%2FPokemonList.vue

### Urql version

@urql/vue: 1.2.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
Hmm, that is correct we might need to change that... Currently we return a [`pause/resume`](https://github.com/urql-graphql/urql/blob/main/packages/vue-urql/src/useQuery.ts#L329-L334) function and only use `args.pause` as the initial value.
