### ISSUE TITLE
(vue) useQuery pause option is not reactive

### ISSUE THREAD

**Issue by mrvik** [urql-graphql/urql#3633]
### Describe the bug

When a reactive property (a ref, computed or reactive) variable is used in the `pause` property, it keeps using the initial value.

### Reproduction

https://stackblitz.com/edit/github-uroxw1-qpmhta?file=package.json

### Urql version

Bug introduced again in >= v1.3.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by angelov-a** [comment]
Experiencing the same issue.
