### ISSUE TITLE
Svelte 5: Support RC version

### ISSUE THREAD

**Issue by OTheNonE** [urql-graphql/urql#3639]
### Describe the bug

Currently, the Svelte package of Urql supports only Official release of Svelte 5, and not the release candidate of Svelte 5:
```
"peerDependencies": {
  "@urql/core": "^5.0.0",
  "svelte": "^3.0.0 || ^4.0.0 || ^5.0.0"
},
```

Can the Svelte package be updated to also support the release candidate of Svelte 5?:
```
"peerDependencies": {
  "@urql/core": "^5.0.0",
  "svelte": "^3.0.0 || ^4.0.0 || ^5.0.0-next.1"
},
```

### Reproduction

-

### Urql version

urql v4.2.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
This doesn't seem right tbh, while Svelte 5 hasn't been released, the PR to add was basically on the assumption that nothing changes for us, and that — at the time of testing — it looked like usage would be unchanged.

To clarify though `^5.0.0` is a range that **includes** pre-releases, e.g. `5.0.0-next.1`. So, if you explicitly install a pre-release (e.g. via a range such as `~5.0.0-next.202`) then you shouldn't see an error. At most, some package managers may choose to warn you about this

**Comment by OTheNonE** [comment]
Sorry, then i must have done something wrong when using @urql/svelte with Svelte 5, npm did not allow me to install the package (without using --force of course). I’ll go ahead and look at the error messages again.

**Comment by kitten** [comment]
Alright, just let us know. I only briefly double-checked this against pnpm

**Comment by itssumitrai** [comment]
@kitten Hi, the RC version for svelte doesn't work with npm install. Can we update with npm semver like what `kit` is doing ?
https://github.com/sveltejs/kit/blob/main/packages/kit/package.json#L50

Its currently blocking us from using Svelte 5 RC
