### ISSUE TITLE
RFC: Augment error extensions type

### ISSUE THREAD

**Issue by musjj** [urql-graphql/urql#3701]
## Summary

GraphQL servers can extend the error type with extensions. An example from this repo:

https://github.com/urql-graphql/urql/blob/7f9cad500040f29aef31769cb4f51b82dedc0ff3/examples/with-refresh-auth/src/client.js#L32-L36

Depending on the server implementation, the shape of the extensions may be uniform across all error responses. In that case, it would be helpful if the client can augment the default `Record<string, any>` with the actual expected type.

## Proposed Solution

Augmenting types can look something like this:

```typescript
declare module "@urql/core" {
  interface Extensions {
    code: "FORBIDDEN" | "INTERNAL_SERVER_ERROR";
  }
}
```

**Comment by JoviDeCroock** [comment]
For our `error` extensions to be configurable `GraphQLJS`/`GraphQL.web` would have to export that as we are using `GraphQLError` which has its own definition of `extensions`. The `extensions` type in `@urql/core` is used for ExecutionResult extensions and IncrementalPayloadExtensions which are a different part of the spec.

What you are looking to alter is in [this part of the spec](https://spec.graphql.org/draft/#sel-GAPHRPZCAACCzG0qP) and would need altering

- [GraphQL.web](https://github.com/0no-co/graphql.web/blob/main/src/types.ts#L5-L7), which also already exports it
- [GraphQL.JS](https://github.com/graphql/graphql-js/blob/16.x.x/src/error/GraphQLError.ts#L19-L21), which already exports it

**Comment by musjj** [comment]
Thank you for merging the PR! Can this repo also be updated with the new version?

**Comment by JoviDeCroock** [comment]
It's a dependency, you can bump this yourself with resolutions

**Comment by musjj** [comment]
The latest version does not include the export change: https://www.npmjs.com/package/@0no-co/graphql.web?activeTab=versions. So, `graphql.web` has to be bumped first.

**Comment by kitten** [comment]
@musjj: We dont't release changes immediately all the time. Please stop commenting for a release that'll come eventually. The action should release a preview version.

Also all of that said, while I understand why @JoviDeCroock has merged this (it's a trivial addition) you really shouldn't be augmenting this type, since there's no type guarantees around error extensions, and should instead write checks and casts for the extensions type.
There's nothing here that's blocking you ✌️
