### ISSUE TITLE
ReferenceError: e is not defined error occurs when running next dev --turbo

### ISSUE THREAD

**Issue by y-hsgw** [urql-graphql/urql#3704]
### Describe the bug

When using` next dev --turbo` with a Next.js application, the following error message appears:
```sh
ReferenceError: e is not defined
    at Module.Kind (/path/to/.next/server/chunks/ssr/node_modules_xyz.js:1376:18)
    at Kind (turbopack://[project]/node_modules/@urql/core/src/gql.ts:84:30)
    ...
```

The application works without issues when running the `next dev` command.

The code is the same as in the following link when the error occurs:
https://github.com/urql-graphql/urql/blob/main/examples/with-next/app/page.tsx

### Reproduction

https://github.com/urql-graphql/urql/tree/main/examples/with-next

### Urql version

- @urql/next: 1.1.2
- urql: 4.2.0
- next: 14.2.16

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
You might have to reload the `turbo` cache apparently when a transitive dep gets bumped, turbo starts failing.

**Comment by y-hsgw** [comment]
I've reloaded the turbo cache, but the issue persists.😢

**Comment by kitten** [comment]
closing this since it's a bug in Next and there's nothing we can do on our end. You can inspect the installed package to verify that the code that is missing in your output bundle is indeed present.

Wiping the turbo cache manually resolves this
