### ISSUE TITLE
graphcache: object has garbled subfields in cache

### ISSUE THREAD

**Issue by ksmoore17** [urql-graphql/urql#3719]
### Describe the bug

Apologies because I have no idea how to title this. I have a schema which, for simplicity's sake, looks like this:
```
schema {
    query: Query
}
type Query {
    organization: Organization!
}
type Organization {
    id: String!
    officials: [Official!]!
    venues: [Venue!]!
}
type Official {
    id: String!
}
type Venue {
    id: String!
}
```
I am using svelte but I don't think that's relevant. I am also generating and providing an `instrospection.json` that I can confirm is accurate. In a nutshell, I have two queries like:
```
query Officials {
    organization {
        id
        officials {
            id
        }
    }
}
```
```
query Venues {
    organization {
        id
        venues {
            id
        }
    }
}
```
All on the same client/cache instance: I execute the `Officials` query, it loads fine. Then the `Venues` query which also loads fine. Then I make the `Officials` query again (and I would expect it to retrieve from the cache) and it provides `{}` as the `organization` object.

Further, any time I execute the `Officials` query, I get this nonsensical warning in the console that matches none of my schema, `introspection.json`, graphql codegen documents, nor my query:
```
Invalid field: The field `officials` does not exist on `Official`, but the GraphQL document expects it to exist.
Traversal will continue, however this may lead to undefined behavior!
(Caused At: "Officials" query)
```
Same with the `Venues` query:
```
Invalid field: The field `venues` does not exist on `Official`, but the GraphQL document expects it to exist.
Traversal will continue, however this may lead to undefined behavior!
(Caused At: "Venues" query)
```

The reason that my schema is like this (there is not an `id` argument on the `organization` field with as you might expect) is because the api is scoped to 1 organization, essentially identified by the url.

Setting the `Organization` type to ignore its `id` field as a cache key solves this.
```
cacheExchange({
    schema,
    keys: {
        Organization: () => null,
        ...
    }
})
```

I guess that I can maybe understand why having this sort of "fake" key on the organization might cause some caching subfields to lose their minds, but the console warnings do not explain that, and somehow I have only just run into the error with the cache being unpopulated on the second query execution.

I will update the reproduction repo when I get a chance.

### Reproduction

https://github.com/ksmoore17/urql-cache-bug-repro

### Urql version

@urql/svelte v4.2.2
@urql/exchange-graphcache v7.2.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
@ksmoore17 your reproduction isn't public so I can't view it 😅 what is most likely happening is the following:

```
// First query fires, this is the resulting link
Query.organization --> Organization:1
Organization:1.id --> 1
Organization:1.officials --> []
// Second query fires, somehow the result of that has a different
// id property
Query.organization --> Organization:2
Organization:2.id --> 2
Organization:2.officials --> 2
Organization:1.id --> 2
Organization:1.venues --> []
// Now GraphCache will reexecute the query and notice, "hey why is venues missing"
```

So the thing to share here would be the results of both queries.

Another question, does your `Query.organization` output a type with the name `Official`? That also looks suspicious to me.

**Comment by ksmoore17** [comment]
Oops sorry about that just made it public.. I couldn’t get it to work with the introspection so the repo won’t run correctly anyways, but I didn’t spend much time with that.
I have a feeling that the ids are not changing, but ill check.
Do you mean a subfield on `organization` with type `Official` or that the `organization` field itself actually returns `Official` somehow. Also unlike in my minimal example, there is a `Query.official` field that returns `Official`, if that’s relevant.
I’ll try to fix the repro shortly

**Comment by ksmoore17** [comment]
Oh wow, I just figured out that this is all because one of the officials has the same uuid as the organization uuid and I'm using `globalIDs: true`. Must have been a copy paste job when setting up the db manually. Thank you for pointing me in the right direction.
